some_add_source(pch.h)
some_add_source(main.cpp)
some_add_source(application.h)
some_add_source(application.cpp)
some_add_source(services/ipc_client_service.h)
some_add_source(services/ipc_client_service.cpp)
