# gate default configuration
listen.host = 127.0.0.1
listen.port = 9000
log.file = logs/gate.log
log.level = info
log.console = true
log.syslog = false
log.rotate.max_size = 10MB
log.rotate.max_files = 5
runtime.daemon = false
