// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipc/common.proto

#include "ipc/common.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace pb {
namespace ipc {
}  // namespace ipc
}  // namespace pb
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ipc_2fcommon_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ipc_2fcommon_2eproto = nullptr;
const uint32_t TableStruct_ipc_2fcommon_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_ipc_2fcommon_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020ipc/common.proto\022\006pb.ipc*\245\002\n\nResultCod"
  "e\022\033\n\027RESULT_CODE_UNSPECIFIED\020\000\022\022\n\016RESULT"
  "_CODE_OK\020\001\022 \n\034RESULT_CODE_INVALID_ARGUME"
  "NT\020\002\022\034\n\030RESULT_CODE_UNAUTHORIZED\020\003\022 \n\034RE"
  "SULT_CODE_PLAYER_NOT_FOUND\020\004\022)\n%RESULT_C"
  "ODE_PLAYER_HELD_BY_OTHER_GAME\020\005\022\037\n\033RESUL"
  "T_CODE_SESSION_EXPIRED\020\006\022\036\n\032RESULT_CODE_"
  "ROUTE_MISMATCH\020\007\022\030\n\024RESULT_CODE_INTERNAL"
  "\020\010*\306\001\n\020DisconnectReason\022!\n\035DISCONNECT_RE"
  "ASON_UNSPECIFIED\020\000\022#\n\037DISCONNECT_REASON_"
  "CLIENT_CLOSED\020\001\022\'\n#DISCONNECT_REASON_HEA"
  "RTBEAT_TIMEOUT\020\002\022\034\n\030DISCONNECT_REASON_KI"
  "CKED\020\003\022#\n\037DISCONNECT_REASON_GATE_SHUTDOW"
  "N\020\004b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_ipc_2fcommon_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ipc_2fcommon_2eproto = {
    false, false, 531, descriptor_table_protodef_ipc_2fcommon_2eproto,
    "ipc/common.proto",
    &descriptor_table_ipc_2fcommon_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_ipc_2fcommon_2eproto::offsets,
    nullptr, file_level_enum_descriptors_ipc_2fcommon_2eproto,
    file_level_service_descriptors_ipc_2fcommon_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ipc_2fcommon_2eproto_getter() {
  return &descriptor_table_ipc_2fcommon_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ipc_2fcommon_2eproto(&descriptor_table_ipc_2fcommon_2eproto);
namespace pb {
namespace ipc {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ResultCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ipc_2fcommon_2eproto);
  return file_level_enum_descriptors_ipc_2fcommon_2eproto[0];
}
bool ResultCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DisconnectReason_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ipc_2fcommon_2eproto);
  return file_level_enum_descriptors_ipc_2fcommon_2eproto[1];
}
bool DisconnectReason_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace ipc
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
