// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipc/player_message.proto

#include "ipc/player_message.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace pb {
namespace ipc {
PROTOBUF_CONSTEXPR ForwardPlayerMessageRequest::ForwardPlayerMessageRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.payload_bytes_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.request_id_)*/uint64_t{0u}
  , /*decltype(_impl_.gate_service_type_)*/0u
  , /*decltype(_impl_.gate_instance_id_)*/0u
  , /*decltype(_impl_.gate_session_id_)*/uint64_t{0u}
  , /*decltype(_impl_.player_id_)*/uint64_t{0u}
  , /*decltype(_impl_.client_sequence_)*/uint64_t{0u}
  , /*decltype(_impl_.timestamp_ms_)*/uint64_t{0u}
  , /*decltype(_impl_.message_id_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ForwardPlayerMessageRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ForwardPlayerMessageRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ForwardPlayerMessageRequestDefaultTypeInternal() {}
  union {
    ForwardPlayerMessageRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ForwardPlayerMessageRequestDefaultTypeInternal _ForwardPlayerMessageRequest_default_instance_;
PROTOBUF_CONSTEXPR ForwardPlayerMessageResponse::ForwardPlayerMessageResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.response_payload_bytes_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.error_message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.request_id_)*/uint64_t{0u}
  , /*decltype(_impl_.player_id_)*/uint64_t{0u}
  , /*decltype(_impl_.message_id_)*/0u
  , /*decltype(_impl_.result_code_)*/0
  , /*decltype(_impl_.server_sequence_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ForwardPlayerMessageResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ForwardPlayerMessageResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ForwardPlayerMessageResponseDefaultTypeInternal() {}
  union {
    ForwardPlayerMessageResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ForwardPlayerMessageResponseDefaultTypeInternal _ForwardPlayerMessageResponse_default_instance_;
}  // namespace ipc
}  // namespace pb
static ::_pb::Metadata file_level_metadata_ipc_2fplayer_5fmessage_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_ipc_2fplayer_5fmessage_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ipc_2fplayer_5fmessage_2eproto = nullptr;

const uint32_t TableStruct_ipc_2fplayer_5fmessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pb::ipc::ForwardPlayerMessageRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::pb::ipc::ForwardPlayerMessageRequest, _impl_.request_id_),
  PROTOBUF_FIELD_OFFSET(::pb::ipc::ForwardPlayerMessageRequest, _impl_.gate_service_type_),
  PROTOBUF_FIELD_OFFSET(::pb::ipc::ForwardPlayerMessageRequest, _impl_.gate_instance_id_),
  PROTOBUF_FIELD_OFFSET(::pb::ipc::ForwardPlayerMessageRequest, _impl_.gate_session_id_),
  PROTOBUF_FIELD_OFFSET(::pb::ipc::ForwardPlayerMessageRequest, _impl_.player_id_),
  PROTOBUF_FIELD_OFFSET(::pb::ipc::ForwardPlayerMessageRequest, _impl_.message_id_),
  PROTOBUF_FIELD_OFFSET(::pb::ipc::ForwardPlayerMessageRequest, _impl_.payload_bytes_),
  PROTOBUF_FIELD_OFFSET(::pb::ipc::ForwardPlayerMessageRequest, _impl_.client_sequence_),
  PROTOBUF_FIELD_OFFSET(::pb::ipc::ForwardPlayerMessageRequest, _impl_.timestamp_ms_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pb::ipc::ForwardPlayerMessageResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::pb::ipc::ForwardPlayerMessageResponse, _impl_.request_id_),
  PROTOBUF_FIELD_OFFSET(::pb::ipc::ForwardPlayerMessageResponse, _impl_.player_id_),
  PROTOBUF_FIELD_OFFSET(::pb::ipc::ForwardPlayerMessageResponse, _impl_.message_id_),
  PROTOBUF_FIELD_OFFSET(::pb::ipc::ForwardPlayerMessageResponse, _impl_.result_code_),
  PROTOBUF_FIELD_OFFSET(::pb::ipc::ForwardPlayerMessageResponse, _impl_.response_payload_bytes_),
  PROTOBUF_FIELD_OFFSET(::pb::ipc::ForwardPlayerMessageResponse, _impl_.server_sequence_),
  PROTOBUF_FIELD_OFFSET(::pb::ipc::ForwardPlayerMessageResponse, _impl_.error_message_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::pb::ipc::ForwardPlayerMessageRequest)},
  { 15, -1, -1, sizeof(::pb::ipc::ForwardPlayerMessageResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::pb::ipc::_ForwardPlayerMessageRequest_default_instance_._instance,
  &::pb::ipc::_ForwardPlayerMessageResponse_default_instance_._instance,
};

const char descriptor_table_protodef_ipc_2fplayer_5fmessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030ipc/player_message.proto\022\006pb.ipc\032\020ipc/"
  "common.proto\"\354\001\n\033ForwardPlayerMessageReq"
  "uest\022\022\n\nrequest_id\030\001 \001(\004\022\031\n\021gate_service"
  "_type\030\002 \001(\r\022\030\n\020gate_instance_id\030\003 \001(\r\022\027\n"
  "\017gate_session_id\030\004 \001(\004\022\021\n\tplayer_id\030\005 \001("
  "\004\022\022\n\nmessage_id\030\006 \001(\r\022\025\n\rpayload_bytes\030\007"
  " \001(\014\022\027\n\017client_sequence\030\010 \001(\004\022\024\n\014timesta"
  "mp_ms\030\t \001(\004\"\322\001\n\034ForwardPlayerMessageResp"
  "onse\022\022\n\nrequest_id\030\001 \001(\004\022\021\n\tplayer_id\030\002 "
  "\001(\004\022\022\n\nmessage_id\030\003 \001(\r\022\'\n\013result_code\030\004"
  " \001(\0162\022.pb.ipc.ResultCode\022\036\n\026response_pay"
  "load_bytes\030\005 \001(\014\022\027\n\017server_sequence\030\006 \001("
  "\004\022\025\n\rerror_message\030\007 \001(\tb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_ipc_2fplayer_5fmessage_2eproto_deps[1] = {
  &::descriptor_table_ipc_2fcommon_2eproto,
};
static ::_pbi::once_flag descriptor_table_ipc_2fplayer_5fmessage_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ipc_2fplayer_5fmessage_2eproto = {
    false, false, 512, descriptor_table_protodef_ipc_2fplayer_5fmessage_2eproto,
    "ipc/player_message.proto",
    &descriptor_table_ipc_2fplayer_5fmessage_2eproto_once, descriptor_table_ipc_2fplayer_5fmessage_2eproto_deps, 1, 2,
    schemas, file_default_instances, TableStruct_ipc_2fplayer_5fmessage_2eproto::offsets,
    file_level_metadata_ipc_2fplayer_5fmessage_2eproto, file_level_enum_descriptors_ipc_2fplayer_5fmessage_2eproto,
    file_level_service_descriptors_ipc_2fplayer_5fmessage_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ipc_2fplayer_5fmessage_2eproto_getter() {
  return &descriptor_table_ipc_2fplayer_5fmessage_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ipc_2fplayer_5fmessage_2eproto(&descriptor_table_ipc_2fplayer_5fmessage_2eproto);
namespace pb {
namespace ipc {

// ===================================================================

class ForwardPlayerMessageRequest::_Internal {
 public:
};

ForwardPlayerMessageRequest::ForwardPlayerMessageRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pb.ipc.ForwardPlayerMessageRequest)
}
ForwardPlayerMessageRequest::ForwardPlayerMessageRequest(const ForwardPlayerMessageRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ForwardPlayerMessageRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.payload_bytes_){}
    , decltype(_impl_.request_id_){}
    , decltype(_impl_.gate_service_type_){}
    , decltype(_impl_.gate_instance_id_){}
    , decltype(_impl_.gate_session_id_){}
    , decltype(_impl_.player_id_){}
    , decltype(_impl_.client_sequence_){}
    , decltype(_impl_.timestamp_ms_){}
    , decltype(_impl_.message_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.payload_bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.payload_bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_payload_bytes().empty()) {
    _this->_impl_.payload_bytes_.Set(from._internal_payload_bytes(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.request_id_, &from._impl_.request_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.message_id_) -
    reinterpret_cast<char*>(&_impl_.request_id_)) + sizeof(_impl_.message_id_));
  // @@protoc_insertion_point(copy_constructor:pb.ipc.ForwardPlayerMessageRequest)
}

inline void ForwardPlayerMessageRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.payload_bytes_){}
    , decltype(_impl_.request_id_){uint64_t{0u}}
    , decltype(_impl_.gate_service_type_){0u}
    , decltype(_impl_.gate_instance_id_){0u}
    , decltype(_impl_.gate_session_id_){uint64_t{0u}}
    , decltype(_impl_.player_id_){uint64_t{0u}}
    , decltype(_impl_.client_sequence_){uint64_t{0u}}
    , decltype(_impl_.timestamp_ms_){uint64_t{0u}}
    , decltype(_impl_.message_id_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.payload_bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.payload_bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ForwardPlayerMessageRequest::~ForwardPlayerMessageRequest() {
  // @@protoc_insertion_point(destructor:pb.ipc.ForwardPlayerMessageRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ForwardPlayerMessageRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.payload_bytes_.Destroy();
}

void ForwardPlayerMessageRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ForwardPlayerMessageRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.ipc.ForwardPlayerMessageRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.payload_bytes_.ClearToEmpty();
  ::memset(&_impl_.request_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.message_id_) -
      reinterpret_cast<char*>(&_impl_.request_id_)) + sizeof(_impl_.message_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ForwardPlayerMessageRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 request_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.request_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 gate_service_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.gate_service_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 gate_instance_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.gate_instance_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 gate_session_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.gate_session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 player_id = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.player_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 message_id = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.message_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes payload_bytes = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_payload_bytes();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 client_sequence = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.client_sequence_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 timestamp_ms = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.timestamp_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ForwardPlayerMessageRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.ipc.ForwardPlayerMessageRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 request_id = 1;
  if (this->_internal_request_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_request_id(), target);
  }

  // uint32 gate_service_type = 2;
  if (this->_internal_gate_service_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_gate_service_type(), target);
  }

  // uint32 gate_instance_id = 3;
  if (this->_internal_gate_instance_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_gate_instance_id(), target);
  }

  // uint64 gate_session_id = 4;
  if (this->_internal_gate_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(4, this->_internal_gate_session_id(), target);
  }

  // uint64 player_id = 5;
  if (this->_internal_player_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(5, this->_internal_player_id(), target);
  }

  // uint32 message_id = 6;
  if (this->_internal_message_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(6, this->_internal_message_id(), target);
  }

  // bytes payload_bytes = 7;
  if (!this->_internal_payload_bytes().empty()) {
    target = stream->WriteBytesMaybeAliased(
        7, this->_internal_payload_bytes(), target);
  }

  // uint64 client_sequence = 8;
  if (this->_internal_client_sequence() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(8, this->_internal_client_sequence(), target);
  }

  // uint64 timestamp_ms = 9;
  if (this->_internal_timestamp_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(9, this->_internal_timestamp_ms(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.ipc.ForwardPlayerMessageRequest)
  return target;
}

size_t ForwardPlayerMessageRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.ipc.ForwardPlayerMessageRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes payload_bytes = 7;
  if (!this->_internal_payload_bytes().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_payload_bytes());
  }

  // uint64 request_id = 1;
  if (this->_internal_request_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_request_id());
  }

  // uint32 gate_service_type = 2;
  if (this->_internal_gate_service_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_gate_service_type());
  }

  // uint32 gate_instance_id = 3;
  if (this->_internal_gate_instance_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_gate_instance_id());
  }

  // uint64 gate_session_id = 4;
  if (this->_internal_gate_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_gate_session_id());
  }

  // uint64 player_id = 5;
  if (this->_internal_player_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_player_id());
  }

  // uint64 client_sequence = 8;
  if (this->_internal_client_sequence() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_client_sequence());
  }

  // uint64 timestamp_ms = 9;
  if (this->_internal_timestamp_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_timestamp_ms());
  }

  // uint32 message_id = 6;
  if (this->_internal_message_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_message_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ForwardPlayerMessageRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ForwardPlayerMessageRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ForwardPlayerMessageRequest::GetClassData() const { return &_class_data_; }


void ForwardPlayerMessageRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ForwardPlayerMessageRequest*>(&to_msg);
  auto& from = static_cast<const ForwardPlayerMessageRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pb.ipc.ForwardPlayerMessageRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_payload_bytes().empty()) {
    _this->_internal_set_payload_bytes(from._internal_payload_bytes());
  }
  if (from._internal_request_id() != 0) {
    _this->_internal_set_request_id(from._internal_request_id());
  }
  if (from._internal_gate_service_type() != 0) {
    _this->_internal_set_gate_service_type(from._internal_gate_service_type());
  }
  if (from._internal_gate_instance_id() != 0) {
    _this->_internal_set_gate_instance_id(from._internal_gate_instance_id());
  }
  if (from._internal_gate_session_id() != 0) {
    _this->_internal_set_gate_session_id(from._internal_gate_session_id());
  }
  if (from._internal_player_id() != 0) {
    _this->_internal_set_player_id(from._internal_player_id());
  }
  if (from._internal_client_sequence() != 0) {
    _this->_internal_set_client_sequence(from._internal_client_sequence());
  }
  if (from._internal_timestamp_ms() != 0) {
    _this->_internal_set_timestamp_ms(from._internal_timestamp_ms());
  }
  if (from._internal_message_id() != 0) {
    _this->_internal_set_message_id(from._internal_message_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ForwardPlayerMessageRequest::CopyFrom(const ForwardPlayerMessageRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.ipc.ForwardPlayerMessageRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ForwardPlayerMessageRequest::IsInitialized() const {
  return true;
}

void ForwardPlayerMessageRequest::InternalSwap(ForwardPlayerMessageRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.payload_bytes_, lhs_arena,
      &other->_impl_.payload_bytes_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ForwardPlayerMessageRequest, _impl_.message_id_)
      + sizeof(ForwardPlayerMessageRequest::_impl_.message_id_)
      - PROTOBUF_FIELD_OFFSET(ForwardPlayerMessageRequest, _impl_.request_id_)>(
          reinterpret_cast<char*>(&_impl_.request_id_),
          reinterpret_cast<char*>(&other->_impl_.request_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ForwardPlayerMessageRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ipc_2fplayer_5fmessage_2eproto_getter, &descriptor_table_ipc_2fplayer_5fmessage_2eproto_once,
      file_level_metadata_ipc_2fplayer_5fmessage_2eproto[0]);
}

// ===================================================================

class ForwardPlayerMessageResponse::_Internal {
 public:
};

ForwardPlayerMessageResponse::ForwardPlayerMessageResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pb.ipc.ForwardPlayerMessageResponse)
}
ForwardPlayerMessageResponse::ForwardPlayerMessageResponse(const ForwardPlayerMessageResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ForwardPlayerMessageResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.response_payload_bytes_){}
    , decltype(_impl_.error_message_){}
    , decltype(_impl_.request_id_){}
    , decltype(_impl_.player_id_){}
    , decltype(_impl_.message_id_){}
    , decltype(_impl_.result_code_){}
    , decltype(_impl_.server_sequence_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.response_payload_bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.response_payload_bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_response_payload_bytes().empty()) {
    _this->_impl_.response_payload_bytes_.Set(from._internal_response_payload_bytes(), 
      _this->GetArenaForAllocation());
  }
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error_message().empty()) {
    _this->_impl_.error_message_.Set(from._internal_error_message(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.request_id_, &from._impl_.request_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.server_sequence_) -
    reinterpret_cast<char*>(&_impl_.request_id_)) + sizeof(_impl_.server_sequence_));
  // @@protoc_insertion_point(copy_constructor:pb.ipc.ForwardPlayerMessageResponse)
}

inline void ForwardPlayerMessageResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.response_payload_bytes_){}
    , decltype(_impl_.error_message_){}
    , decltype(_impl_.request_id_){uint64_t{0u}}
    , decltype(_impl_.player_id_){uint64_t{0u}}
    , decltype(_impl_.message_id_){0u}
    , decltype(_impl_.result_code_){0}
    , decltype(_impl_.server_sequence_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.response_payload_bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.response_payload_bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ForwardPlayerMessageResponse::~ForwardPlayerMessageResponse() {
  // @@protoc_insertion_point(destructor:pb.ipc.ForwardPlayerMessageResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ForwardPlayerMessageResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.response_payload_bytes_.Destroy();
  _impl_.error_message_.Destroy();
}

void ForwardPlayerMessageResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ForwardPlayerMessageResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.ipc.ForwardPlayerMessageResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.response_payload_bytes_.ClearToEmpty();
  _impl_.error_message_.ClearToEmpty();
  ::memset(&_impl_.request_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.server_sequence_) -
      reinterpret_cast<char*>(&_impl_.request_id_)) + sizeof(_impl_.server_sequence_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ForwardPlayerMessageResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 request_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.request_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 player_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.player_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 message_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.message_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .pb.ipc.ResultCode result_code = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_result_code(static_cast<::pb::ipc::ResultCode>(val));
        } else
          goto handle_unusual;
        continue;
      // bytes response_payload_bytes = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_response_payload_bytes();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 server_sequence = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.server_sequence_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string error_message = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_error_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "pb.ipc.ForwardPlayerMessageResponse.error_message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ForwardPlayerMessageResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.ipc.ForwardPlayerMessageResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 request_id = 1;
  if (this->_internal_request_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_request_id(), target);
  }

  // uint64 player_id = 2;
  if (this->_internal_player_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_player_id(), target);
  }

  // uint32 message_id = 3;
  if (this->_internal_message_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_message_id(), target);
  }

  // .pb.ipc.ResultCode result_code = 4;
  if (this->_internal_result_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      4, this->_internal_result_code(), target);
  }

  // bytes response_payload_bytes = 5;
  if (!this->_internal_response_payload_bytes().empty()) {
    target = stream->WriteBytesMaybeAliased(
        5, this->_internal_response_payload_bytes(), target);
  }

  // uint64 server_sequence = 6;
  if (this->_internal_server_sequence() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(6, this->_internal_server_sequence(), target);
  }

  // string error_message = 7;
  if (!this->_internal_error_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error_message().data(), static_cast<int>(this->_internal_error_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb.ipc.ForwardPlayerMessageResponse.error_message");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_error_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.ipc.ForwardPlayerMessageResponse)
  return target;
}

size_t ForwardPlayerMessageResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.ipc.ForwardPlayerMessageResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes response_payload_bytes = 5;
  if (!this->_internal_response_payload_bytes().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_response_payload_bytes());
  }

  // string error_message = 7;
  if (!this->_internal_error_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error_message());
  }

  // uint64 request_id = 1;
  if (this->_internal_request_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_request_id());
  }

  // uint64 player_id = 2;
  if (this->_internal_player_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_player_id());
  }

  // uint32 message_id = 3;
  if (this->_internal_message_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_message_id());
  }

  // .pb.ipc.ResultCode result_code = 4;
  if (this->_internal_result_code() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_result_code());
  }

  // uint64 server_sequence = 6;
  if (this->_internal_server_sequence() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_server_sequence());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ForwardPlayerMessageResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ForwardPlayerMessageResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ForwardPlayerMessageResponse::GetClassData() const { return &_class_data_; }


void ForwardPlayerMessageResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ForwardPlayerMessageResponse*>(&to_msg);
  auto& from = static_cast<const ForwardPlayerMessageResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pb.ipc.ForwardPlayerMessageResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_response_payload_bytes().empty()) {
    _this->_internal_set_response_payload_bytes(from._internal_response_payload_bytes());
  }
  if (!from._internal_error_message().empty()) {
    _this->_internal_set_error_message(from._internal_error_message());
  }
  if (from._internal_request_id() != 0) {
    _this->_internal_set_request_id(from._internal_request_id());
  }
  if (from._internal_player_id() != 0) {
    _this->_internal_set_player_id(from._internal_player_id());
  }
  if (from._internal_message_id() != 0) {
    _this->_internal_set_message_id(from._internal_message_id());
  }
  if (from._internal_result_code() != 0) {
    _this->_internal_set_result_code(from._internal_result_code());
  }
  if (from._internal_server_sequence() != 0) {
    _this->_internal_set_server_sequence(from._internal_server_sequence());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ForwardPlayerMessageResponse::CopyFrom(const ForwardPlayerMessageResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.ipc.ForwardPlayerMessageResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ForwardPlayerMessageResponse::IsInitialized() const {
  return true;
}

void ForwardPlayerMessageResponse::InternalSwap(ForwardPlayerMessageResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.response_payload_bytes_, lhs_arena,
      &other->_impl_.response_payload_bytes_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_message_, lhs_arena,
      &other->_impl_.error_message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ForwardPlayerMessageResponse, _impl_.server_sequence_)
      + sizeof(ForwardPlayerMessageResponse::_impl_.server_sequence_)
      - PROTOBUF_FIELD_OFFSET(ForwardPlayerMessageResponse, _impl_.request_id_)>(
          reinterpret_cast<char*>(&_impl_.request_id_),
          reinterpret_cast<char*>(&other->_impl_.request_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ForwardPlayerMessageResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ipc_2fplayer_5fmessage_2eproto_getter, &descriptor_table_ipc_2fplayer_5fmessage_2eproto_once,
      file_level_metadata_ipc_2fplayer_5fmessage_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ipc
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::pb::ipc::ForwardPlayerMessageRequest*
Arena::CreateMaybeMessage< ::pb::ipc::ForwardPlayerMessageRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pb::ipc::ForwardPlayerMessageRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::pb::ipc::ForwardPlayerMessageResponse*
Arena::CreateMaybeMessage< ::pb::ipc::ForwardPlayerMessageResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pb::ipc::ForwardPlayerMessageResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
