// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipc/session.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ipc_2fsession_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ipc_2fsession_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ipc/common.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ipc_2fsession_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ipc_2fsession_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ipc_2fsession_2eproto;
namespace pb {
namespace ipc {
class BindPlayerSession;
struct BindPlayerSessionDefaultTypeInternal;
extern BindPlayerSessionDefaultTypeInternal _BindPlayerSession_default_instance_;
class KickAccountSession;
struct KickAccountSessionDefaultTypeInternal;
extern KickAccountSessionDefaultTypeInternal _KickAccountSession_default_instance_;
class KickAccountSessionAck;
struct KickAccountSessionAckDefaultTypeInternal;
extern KickAccountSessionAckDefaultTypeInternal _KickAccountSessionAck_default_instance_;
class PlayerDisconnected;
struct PlayerDisconnectedDefaultTypeInternal;
extern PlayerDisconnectedDefaultTypeInternal _PlayerDisconnected_default_instance_;
class UnbindPlayerSession;
struct UnbindPlayerSessionDefaultTypeInternal;
extern UnbindPlayerSessionDefaultTypeInternal _UnbindPlayerSession_default_instance_;
}  // namespace ipc
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> ::pb::ipc::BindPlayerSession* Arena::CreateMaybeMessage<::pb::ipc::BindPlayerSession>(Arena*);
template<> ::pb::ipc::KickAccountSession* Arena::CreateMaybeMessage<::pb::ipc::KickAccountSession>(Arena*);
template<> ::pb::ipc::KickAccountSessionAck* Arena::CreateMaybeMessage<::pb::ipc::KickAccountSessionAck>(Arena*);
template<> ::pb::ipc::PlayerDisconnected* Arena::CreateMaybeMessage<::pb::ipc::PlayerDisconnected>(Arena*);
template<> ::pb::ipc::UnbindPlayerSession* Arena::CreateMaybeMessage<::pb::ipc::UnbindPlayerSession>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pb {
namespace ipc {

// ===================================================================

class KickAccountSession final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.ipc.KickAccountSession) */ {
 public:
  inline KickAccountSession() : KickAccountSession(nullptr) {}
  ~KickAccountSession() override;
  explicit PROTOBUF_CONSTEXPR KickAccountSession(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  KickAccountSession(const KickAccountSession& from);
  KickAccountSession(KickAccountSession&& from) noexcept
    : KickAccountSession() {
    *this = ::std::move(from);
  }

  inline KickAccountSession& operator=(const KickAccountSession& from) {
    CopyFrom(from);
    return *this;
  }
  inline KickAccountSession& operator=(KickAccountSession&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const KickAccountSession& default_instance() {
    return *internal_default_instance();
  }
  static inline const KickAccountSession* internal_default_instance() {
    return reinterpret_cast<const KickAccountSession*>(
               &_KickAccountSession_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(KickAccountSession& a, KickAccountSession& b) {
    a.Swap(&b);
  }
  inline void Swap(KickAccountSession* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(KickAccountSession* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  KickAccountSession* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<KickAccountSession>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const KickAccountSession& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const KickAccountSession& from) {
    KickAccountSession::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KickAccountSession* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.ipc.KickAccountSession";
  }
  protected:
  explicit KickAccountSession(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountIdFieldNumber = 2,
    kReasonFieldNumber = 8,
    kRequestIdFieldNumber = 1,
    kOldGateServiceTypeFieldNumber = 3,
    kOldGateInstanceIdFieldNumber = 4,
    kOldGateSessionIdFieldNumber = 5,
    kNewGateServiceTypeFieldNumber = 6,
    kNewGateInstanceIdFieldNumber = 7,
  };
  // string account_id = 2;
  void clear_account_id();
  const std::string& account_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_account_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_account_id();
  PROTOBUF_NODISCARD std::string* release_account_id();
  void set_allocated_account_id(std::string* account_id);
  private:
  const std::string& _internal_account_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_account_id(const std::string& value);
  std::string* _internal_mutable_account_id();
  public:

  // string reason = 8;
  void clear_reason();
  const std::string& reason() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_reason(ArgT0&& arg0, ArgT... args);
  std::string* mutable_reason();
  PROTOBUF_NODISCARD std::string* release_reason();
  void set_allocated_reason(std::string* reason);
  private:
  const std::string& _internal_reason() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_reason(const std::string& value);
  std::string* _internal_mutable_reason();
  public:

  // uint64 request_id = 1;
  void clear_request_id();
  uint64_t request_id() const;
  void set_request_id(uint64_t value);
  private:
  uint64_t _internal_request_id() const;
  void _internal_set_request_id(uint64_t value);
  public:

  // uint32 old_gate_service_type = 3;
  void clear_old_gate_service_type();
  uint32_t old_gate_service_type() const;
  void set_old_gate_service_type(uint32_t value);
  private:
  uint32_t _internal_old_gate_service_type() const;
  void _internal_set_old_gate_service_type(uint32_t value);
  public:

  // uint32 old_gate_instance_id = 4;
  void clear_old_gate_instance_id();
  uint32_t old_gate_instance_id() const;
  void set_old_gate_instance_id(uint32_t value);
  private:
  uint32_t _internal_old_gate_instance_id() const;
  void _internal_set_old_gate_instance_id(uint32_t value);
  public:

  // uint64 old_gate_session_id = 5;
  void clear_old_gate_session_id();
  uint64_t old_gate_session_id() const;
  void set_old_gate_session_id(uint64_t value);
  private:
  uint64_t _internal_old_gate_session_id() const;
  void _internal_set_old_gate_session_id(uint64_t value);
  public:

  // uint32 new_gate_service_type = 6;
  void clear_new_gate_service_type();
  uint32_t new_gate_service_type() const;
  void set_new_gate_service_type(uint32_t value);
  private:
  uint32_t _internal_new_gate_service_type() const;
  void _internal_set_new_gate_service_type(uint32_t value);
  public:

  // uint32 new_gate_instance_id = 7;
  void clear_new_gate_instance_id();
  uint32_t new_gate_instance_id() const;
  void set_new_gate_instance_id(uint32_t value);
  private:
  uint32_t _internal_new_gate_instance_id() const;
  void _internal_set_new_gate_instance_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:pb.ipc.KickAccountSession)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr account_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr reason_;
    uint64_t request_id_;
    uint32_t old_gate_service_type_;
    uint32_t old_gate_instance_id_;
    uint64_t old_gate_session_id_;
    uint32_t new_gate_service_type_;
    uint32_t new_gate_instance_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ipc_2fsession_2eproto;
};
// -------------------------------------------------------------------

class KickAccountSessionAck final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.ipc.KickAccountSessionAck) */ {
 public:
  inline KickAccountSessionAck() : KickAccountSessionAck(nullptr) {}
  ~KickAccountSessionAck() override;
  explicit PROTOBUF_CONSTEXPR KickAccountSessionAck(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  KickAccountSessionAck(const KickAccountSessionAck& from);
  KickAccountSessionAck(KickAccountSessionAck&& from) noexcept
    : KickAccountSessionAck() {
    *this = ::std::move(from);
  }

  inline KickAccountSessionAck& operator=(const KickAccountSessionAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline KickAccountSessionAck& operator=(KickAccountSessionAck&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const KickAccountSessionAck& default_instance() {
    return *internal_default_instance();
  }
  static inline const KickAccountSessionAck* internal_default_instance() {
    return reinterpret_cast<const KickAccountSessionAck*>(
               &_KickAccountSessionAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(KickAccountSessionAck& a, KickAccountSessionAck& b) {
    a.Swap(&b);
  }
  inline void Swap(KickAccountSessionAck* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(KickAccountSessionAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  KickAccountSessionAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<KickAccountSessionAck>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const KickAccountSessionAck& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const KickAccountSessionAck& from) {
    KickAccountSessionAck::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KickAccountSessionAck* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.ipc.KickAccountSessionAck";
  }
  protected:
  explicit KickAccountSessionAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountIdFieldNumber = 3,
    kRequestIdFieldNumber = 1,
    kOldGateSessionIdFieldNumber = 4,
    kResultCodeFieldNumber = 2,
  };
  // string account_id = 3;
  void clear_account_id();
  const std::string& account_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_account_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_account_id();
  PROTOBUF_NODISCARD std::string* release_account_id();
  void set_allocated_account_id(std::string* account_id);
  private:
  const std::string& _internal_account_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_account_id(const std::string& value);
  std::string* _internal_mutable_account_id();
  public:

  // uint64 request_id = 1;
  void clear_request_id();
  uint64_t request_id() const;
  void set_request_id(uint64_t value);
  private:
  uint64_t _internal_request_id() const;
  void _internal_set_request_id(uint64_t value);
  public:

  // uint64 old_gate_session_id = 4;
  void clear_old_gate_session_id();
  uint64_t old_gate_session_id() const;
  void set_old_gate_session_id(uint64_t value);
  private:
  uint64_t _internal_old_gate_session_id() const;
  void _internal_set_old_gate_session_id(uint64_t value);
  public:

  // .pb.ipc.ResultCode result_code = 2;
  void clear_result_code();
  ::pb::ipc::ResultCode result_code() const;
  void set_result_code(::pb::ipc::ResultCode value);
  private:
  ::pb::ipc::ResultCode _internal_result_code() const;
  void _internal_set_result_code(::pb::ipc::ResultCode value);
  public:

  // @@protoc_insertion_point(class_scope:pb.ipc.KickAccountSessionAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr account_id_;
    uint64_t request_id_;
    uint64_t old_gate_session_id_;
    int result_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ipc_2fsession_2eproto;
};
// -------------------------------------------------------------------

class PlayerDisconnected final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.ipc.PlayerDisconnected) */ {
 public:
  inline PlayerDisconnected() : PlayerDisconnected(nullptr) {}
  ~PlayerDisconnected() override;
  explicit PROTOBUF_CONSTEXPR PlayerDisconnected(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerDisconnected(const PlayerDisconnected& from);
  PlayerDisconnected(PlayerDisconnected&& from) noexcept
    : PlayerDisconnected() {
    *this = ::std::move(from);
  }

  inline PlayerDisconnected& operator=(const PlayerDisconnected& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerDisconnected& operator=(PlayerDisconnected&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerDisconnected& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerDisconnected* internal_default_instance() {
    return reinterpret_cast<const PlayerDisconnected*>(
               &_PlayerDisconnected_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PlayerDisconnected& a, PlayerDisconnected& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerDisconnected* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerDisconnected* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerDisconnected* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerDisconnected>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerDisconnected& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerDisconnected& from) {
    PlayerDisconnected::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerDisconnected* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.ipc.PlayerDisconnected";
  }
  protected:
  explicit PlayerDisconnected(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdFieldNumber = 1,
    kGateServiceTypeFieldNumber = 2,
    kGateInstanceIdFieldNumber = 3,
    kGateSessionIdFieldNumber = 4,
    kOccurredAtMsFieldNumber = 6,
    kReasonFieldNumber = 5,
  };
  // uint64 player_id = 1;
  void clear_player_id();
  uint64_t player_id() const;
  void set_player_id(uint64_t value);
  private:
  uint64_t _internal_player_id() const;
  void _internal_set_player_id(uint64_t value);
  public:

  // uint32 gate_service_type = 2;
  void clear_gate_service_type();
  uint32_t gate_service_type() const;
  void set_gate_service_type(uint32_t value);
  private:
  uint32_t _internal_gate_service_type() const;
  void _internal_set_gate_service_type(uint32_t value);
  public:

  // uint32 gate_instance_id = 3;
  void clear_gate_instance_id();
  uint32_t gate_instance_id() const;
  void set_gate_instance_id(uint32_t value);
  private:
  uint32_t _internal_gate_instance_id() const;
  void _internal_set_gate_instance_id(uint32_t value);
  public:

  // uint64 gate_session_id = 4;
  void clear_gate_session_id();
  uint64_t gate_session_id() const;
  void set_gate_session_id(uint64_t value);
  private:
  uint64_t _internal_gate_session_id() const;
  void _internal_set_gate_session_id(uint64_t value);
  public:

  // uint64 occurred_at_ms = 6;
  void clear_occurred_at_ms();
  uint64_t occurred_at_ms() const;
  void set_occurred_at_ms(uint64_t value);
  private:
  uint64_t _internal_occurred_at_ms() const;
  void _internal_set_occurred_at_ms(uint64_t value);
  public:

  // .pb.ipc.DisconnectReason reason = 5;
  void clear_reason();
  ::pb::ipc::DisconnectReason reason() const;
  void set_reason(::pb::ipc::DisconnectReason value);
  private:
  ::pb::ipc::DisconnectReason _internal_reason() const;
  void _internal_set_reason(::pb::ipc::DisconnectReason value);
  public:

  // @@protoc_insertion_point(class_scope:pb.ipc.PlayerDisconnected)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t player_id_;
    uint32_t gate_service_type_;
    uint32_t gate_instance_id_;
    uint64_t gate_session_id_;
    uint64_t occurred_at_ms_;
    int reason_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ipc_2fsession_2eproto;
};
// -------------------------------------------------------------------

class BindPlayerSession final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.ipc.BindPlayerSession) */ {
 public:
  inline BindPlayerSession() : BindPlayerSession(nullptr) {}
  ~BindPlayerSession() override;
  explicit PROTOBUF_CONSTEXPR BindPlayerSession(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BindPlayerSession(const BindPlayerSession& from);
  BindPlayerSession(BindPlayerSession&& from) noexcept
    : BindPlayerSession() {
    *this = ::std::move(from);
  }

  inline BindPlayerSession& operator=(const BindPlayerSession& from) {
    CopyFrom(from);
    return *this;
  }
  inline BindPlayerSession& operator=(BindPlayerSession&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BindPlayerSession& default_instance() {
    return *internal_default_instance();
  }
  static inline const BindPlayerSession* internal_default_instance() {
    return reinterpret_cast<const BindPlayerSession*>(
               &_BindPlayerSession_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(BindPlayerSession& a, BindPlayerSession& b) {
    a.Swap(&b);
  }
  inline void Swap(BindPlayerSession* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BindPlayerSession* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BindPlayerSession* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BindPlayerSession>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BindPlayerSession& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BindPlayerSession& from) {
    BindPlayerSession::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BindPlayerSession* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.ipc.BindPlayerSession";
  }
  protected:
  explicit BindPlayerSession(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdFieldNumber = 1,
    kGateServiceTypeFieldNumber = 2,
    kGateInstanceIdFieldNumber = 3,
    kGateSessionIdFieldNumber = 4,
  };
  // uint64 player_id = 1;
  void clear_player_id();
  uint64_t player_id() const;
  void set_player_id(uint64_t value);
  private:
  uint64_t _internal_player_id() const;
  void _internal_set_player_id(uint64_t value);
  public:

  // uint32 gate_service_type = 2;
  void clear_gate_service_type();
  uint32_t gate_service_type() const;
  void set_gate_service_type(uint32_t value);
  private:
  uint32_t _internal_gate_service_type() const;
  void _internal_set_gate_service_type(uint32_t value);
  public:

  // uint32 gate_instance_id = 3;
  void clear_gate_instance_id();
  uint32_t gate_instance_id() const;
  void set_gate_instance_id(uint32_t value);
  private:
  uint32_t _internal_gate_instance_id() const;
  void _internal_set_gate_instance_id(uint32_t value);
  public:

  // uint64 gate_session_id = 4;
  void clear_gate_session_id();
  uint64_t gate_session_id() const;
  void set_gate_session_id(uint64_t value);
  private:
  uint64_t _internal_gate_session_id() const;
  void _internal_set_gate_session_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:pb.ipc.BindPlayerSession)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t player_id_;
    uint32_t gate_service_type_;
    uint32_t gate_instance_id_;
    uint64_t gate_session_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ipc_2fsession_2eproto;
};
// -------------------------------------------------------------------

class UnbindPlayerSession final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.ipc.UnbindPlayerSession) */ {
 public:
  inline UnbindPlayerSession() : UnbindPlayerSession(nullptr) {}
  ~UnbindPlayerSession() override;
  explicit PROTOBUF_CONSTEXPR UnbindPlayerSession(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UnbindPlayerSession(const UnbindPlayerSession& from);
  UnbindPlayerSession(UnbindPlayerSession&& from) noexcept
    : UnbindPlayerSession() {
    *this = ::std::move(from);
  }

  inline UnbindPlayerSession& operator=(const UnbindPlayerSession& from) {
    CopyFrom(from);
    return *this;
  }
  inline UnbindPlayerSession& operator=(UnbindPlayerSession&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UnbindPlayerSession& default_instance() {
    return *internal_default_instance();
  }
  static inline const UnbindPlayerSession* internal_default_instance() {
    return reinterpret_cast<const UnbindPlayerSession*>(
               &_UnbindPlayerSession_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(UnbindPlayerSession& a, UnbindPlayerSession& b) {
    a.Swap(&b);
  }
  inline void Swap(UnbindPlayerSession* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UnbindPlayerSession* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UnbindPlayerSession* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UnbindPlayerSession>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UnbindPlayerSession& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UnbindPlayerSession& from) {
    UnbindPlayerSession::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UnbindPlayerSession* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.ipc.UnbindPlayerSession";
  }
  protected:
  explicit UnbindPlayerSession(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdFieldNumber = 1,
    kGateServiceTypeFieldNumber = 2,
    kGateInstanceIdFieldNumber = 3,
    kGateSessionIdFieldNumber = 4,
    kReasonFieldNumber = 5,
  };
  // uint64 player_id = 1;
  void clear_player_id();
  uint64_t player_id() const;
  void set_player_id(uint64_t value);
  private:
  uint64_t _internal_player_id() const;
  void _internal_set_player_id(uint64_t value);
  public:

  // uint32 gate_service_type = 2;
  void clear_gate_service_type();
  uint32_t gate_service_type() const;
  void set_gate_service_type(uint32_t value);
  private:
  uint32_t _internal_gate_service_type() const;
  void _internal_set_gate_service_type(uint32_t value);
  public:

  // uint32 gate_instance_id = 3;
  void clear_gate_instance_id();
  uint32_t gate_instance_id() const;
  void set_gate_instance_id(uint32_t value);
  private:
  uint32_t _internal_gate_instance_id() const;
  void _internal_set_gate_instance_id(uint32_t value);
  public:

  // uint64 gate_session_id = 4;
  void clear_gate_session_id();
  uint64_t gate_session_id() const;
  void set_gate_session_id(uint64_t value);
  private:
  uint64_t _internal_gate_session_id() const;
  void _internal_set_gate_session_id(uint64_t value);
  public:

  // .pb.ipc.DisconnectReason reason = 5;
  void clear_reason();
  ::pb::ipc::DisconnectReason reason() const;
  void set_reason(::pb::ipc::DisconnectReason value);
  private:
  ::pb::ipc::DisconnectReason _internal_reason() const;
  void _internal_set_reason(::pb::ipc::DisconnectReason value);
  public:

  // @@protoc_insertion_point(class_scope:pb.ipc.UnbindPlayerSession)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t player_id_;
    uint32_t gate_service_type_;
    uint32_t gate_instance_id_;
    uint64_t gate_session_id_;
    int reason_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ipc_2fsession_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// KickAccountSession

// uint64 request_id = 1;
inline void KickAccountSession::clear_request_id() {
  _impl_.request_id_ = uint64_t{0u};
}
inline uint64_t KickAccountSession::_internal_request_id() const {
  return _impl_.request_id_;
}
inline uint64_t KickAccountSession::request_id() const {
  // @@protoc_insertion_point(field_get:pb.ipc.KickAccountSession.request_id)
  return _internal_request_id();
}
inline void KickAccountSession::_internal_set_request_id(uint64_t value) {
  
  _impl_.request_id_ = value;
}
inline void KickAccountSession::set_request_id(uint64_t value) {
  _internal_set_request_id(value);
  // @@protoc_insertion_point(field_set:pb.ipc.KickAccountSession.request_id)
}

// string account_id = 2;
inline void KickAccountSession::clear_account_id() {
  _impl_.account_id_.ClearToEmpty();
}
inline const std::string& KickAccountSession::account_id() const {
  // @@protoc_insertion_point(field_get:pb.ipc.KickAccountSession.account_id)
  return _internal_account_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void KickAccountSession::set_account_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.account_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb.ipc.KickAccountSession.account_id)
}
inline std::string* KickAccountSession::mutable_account_id() {
  std::string* _s = _internal_mutable_account_id();
  // @@protoc_insertion_point(field_mutable:pb.ipc.KickAccountSession.account_id)
  return _s;
}
inline const std::string& KickAccountSession::_internal_account_id() const {
  return _impl_.account_id_.Get();
}
inline void KickAccountSession::_internal_set_account_id(const std::string& value) {
  
  _impl_.account_id_.Set(value, GetArenaForAllocation());
}
inline std::string* KickAccountSession::_internal_mutable_account_id() {
  
  return _impl_.account_id_.Mutable(GetArenaForAllocation());
}
inline std::string* KickAccountSession::release_account_id() {
  // @@protoc_insertion_point(field_release:pb.ipc.KickAccountSession.account_id)
  return _impl_.account_id_.Release();
}
inline void KickAccountSession::set_allocated_account_id(std::string* account_id) {
  if (account_id != nullptr) {
    
  } else {
    
  }
  _impl_.account_id_.SetAllocated(account_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.account_id_.IsDefault()) {
    _impl_.account_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb.ipc.KickAccountSession.account_id)
}

// uint32 old_gate_service_type = 3;
inline void KickAccountSession::clear_old_gate_service_type() {
  _impl_.old_gate_service_type_ = 0u;
}
inline uint32_t KickAccountSession::_internal_old_gate_service_type() const {
  return _impl_.old_gate_service_type_;
}
inline uint32_t KickAccountSession::old_gate_service_type() const {
  // @@protoc_insertion_point(field_get:pb.ipc.KickAccountSession.old_gate_service_type)
  return _internal_old_gate_service_type();
}
inline void KickAccountSession::_internal_set_old_gate_service_type(uint32_t value) {
  
  _impl_.old_gate_service_type_ = value;
}
inline void KickAccountSession::set_old_gate_service_type(uint32_t value) {
  _internal_set_old_gate_service_type(value);
  // @@protoc_insertion_point(field_set:pb.ipc.KickAccountSession.old_gate_service_type)
}

// uint32 old_gate_instance_id = 4;
inline void KickAccountSession::clear_old_gate_instance_id() {
  _impl_.old_gate_instance_id_ = 0u;
}
inline uint32_t KickAccountSession::_internal_old_gate_instance_id() const {
  return _impl_.old_gate_instance_id_;
}
inline uint32_t KickAccountSession::old_gate_instance_id() const {
  // @@protoc_insertion_point(field_get:pb.ipc.KickAccountSession.old_gate_instance_id)
  return _internal_old_gate_instance_id();
}
inline void KickAccountSession::_internal_set_old_gate_instance_id(uint32_t value) {
  
  _impl_.old_gate_instance_id_ = value;
}
inline void KickAccountSession::set_old_gate_instance_id(uint32_t value) {
  _internal_set_old_gate_instance_id(value);
  // @@protoc_insertion_point(field_set:pb.ipc.KickAccountSession.old_gate_instance_id)
}

// uint64 old_gate_session_id = 5;
inline void KickAccountSession::clear_old_gate_session_id() {
  _impl_.old_gate_session_id_ = uint64_t{0u};
}
inline uint64_t KickAccountSession::_internal_old_gate_session_id() const {
  return _impl_.old_gate_session_id_;
}
inline uint64_t KickAccountSession::old_gate_session_id() const {
  // @@protoc_insertion_point(field_get:pb.ipc.KickAccountSession.old_gate_session_id)
  return _internal_old_gate_session_id();
}
inline void KickAccountSession::_internal_set_old_gate_session_id(uint64_t value) {
  
  _impl_.old_gate_session_id_ = value;
}
inline void KickAccountSession::set_old_gate_session_id(uint64_t value) {
  _internal_set_old_gate_session_id(value);
  // @@protoc_insertion_point(field_set:pb.ipc.KickAccountSession.old_gate_session_id)
}

// uint32 new_gate_service_type = 6;
inline void KickAccountSession::clear_new_gate_service_type() {
  _impl_.new_gate_service_type_ = 0u;
}
inline uint32_t KickAccountSession::_internal_new_gate_service_type() const {
  return _impl_.new_gate_service_type_;
}
inline uint32_t KickAccountSession::new_gate_service_type() const {
  // @@protoc_insertion_point(field_get:pb.ipc.KickAccountSession.new_gate_service_type)
  return _internal_new_gate_service_type();
}
inline void KickAccountSession::_internal_set_new_gate_service_type(uint32_t value) {
  
  _impl_.new_gate_service_type_ = value;
}
inline void KickAccountSession::set_new_gate_service_type(uint32_t value) {
  _internal_set_new_gate_service_type(value);
  // @@protoc_insertion_point(field_set:pb.ipc.KickAccountSession.new_gate_service_type)
}

// uint32 new_gate_instance_id = 7;
inline void KickAccountSession::clear_new_gate_instance_id() {
  _impl_.new_gate_instance_id_ = 0u;
}
inline uint32_t KickAccountSession::_internal_new_gate_instance_id() const {
  return _impl_.new_gate_instance_id_;
}
inline uint32_t KickAccountSession::new_gate_instance_id() const {
  // @@protoc_insertion_point(field_get:pb.ipc.KickAccountSession.new_gate_instance_id)
  return _internal_new_gate_instance_id();
}
inline void KickAccountSession::_internal_set_new_gate_instance_id(uint32_t value) {
  
  _impl_.new_gate_instance_id_ = value;
}
inline void KickAccountSession::set_new_gate_instance_id(uint32_t value) {
  _internal_set_new_gate_instance_id(value);
  // @@protoc_insertion_point(field_set:pb.ipc.KickAccountSession.new_gate_instance_id)
}

// string reason = 8;
inline void KickAccountSession::clear_reason() {
  _impl_.reason_.ClearToEmpty();
}
inline const std::string& KickAccountSession::reason() const {
  // @@protoc_insertion_point(field_get:pb.ipc.KickAccountSession.reason)
  return _internal_reason();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void KickAccountSession::set_reason(ArgT0&& arg0, ArgT... args) {
 
 _impl_.reason_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb.ipc.KickAccountSession.reason)
}
inline std::string* KickAccountSession::mutable_reason() {
  std::string* _s = _internal_mutable_reason();
  // @@protoc_insertion_point(field_mutable:pb.ipc.KickAccountSession.reason)
  return _s;
}
inline const std::string& KickAccountSession::_internal_reason() const {
  return _impl_.reason_.Get();
}
inline void KickAccountSession::_internal_set_reason(const std::string& value) {
  
  _impl_.reason_.Set(value, GetArenaForAllocation());
}
inline std::string* KickAccountSession::_internal_mutable_reason() {
  
  return _impl_.reason_.Mutable(GetArenaForAllocation());
}
inline std::string* KickAccountSession::release_reason() {
  // @@protoc_insertion_point(field_release:pb.ipc.KickAccountSession.reason)
  return _impl_.reason_.Release();
}
inline void KickAccountSession::set_allocated_reason(std::string* reason) {
  if (reason != nullptr) {
    
  } else {
    
  }
  _impl_.reason_.SetAllocated(reason, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.reason_.IsDefault()) {
    _impl_.reason_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb.ipc.KickAccountSession.reason)
}

// -------------------------------------------------------------------

// KickAccountSessionAck

// uint64 request_id = 1;
inline void KickAccountSessionAck::clear_request_id() {
  _impl_.request_id_ = uint64_t{0u};
}
inline uint64_t KickAccountSessionAck::_internal_request_id() const {
  return _impl_.request_id_;
}
inline uint64_t KickAccountSessionAck::request_id() const {
  // @@protoc_insertion_point(field_get:pb.ipc.KickAccountSessionAck.request_id)
  return _internal_request_id();
}
inline void KickAccountSessionAck::_internal_set_request_id(uint64_t value) {
  
  _impl_.request_id_ = value;
}
inline void KickAccountSessionAck::set_request_id(uint64_t value) {
  _internal_set_request_id(value);
  // @@protoc_insertion_point(field_set:pb.ipc.KickAccountSessionAck.request_id)
}

// .pb.ipc.ResultCode result_code = 2;
inline void KickAccountSessionAck::clear_result_code() {
  _impl_.result_code_ = 0;
}
inline ::pb::ipc::ResultCode KickAccountSessionAck::_internal_result_code() const {
  return static_cast< ::pb::ipc::ResultCode >(_impl_.result_code_);
}
inline ::pb::ipc::ResultCode KickAccountSessionAck::result_code() const {
  // @@protoc_insertion_point(field_get:pb.ipc.KickAccountSessionAck.result_code)
  return _internal_result_code();
}
inline void KickAccountSessionAck::_internal_set_result_code(::pb::ipc::ResultCode value) {
  
  _impl_.result_code_ = value;
}
inline void KickAccountSessionAck::set_result_code(::pb::ipc::ResultCode value) {
  _internal_set_result_code(value);
  // @@protoc_insertion_point(field_set:pb.ipc.KickAccountSessionAck.result_code)
}

// string account_id = 3;
inline void KickAccountSessionAck::clear_account_id() {
  _impl_.account_id_.ClearToEmpty();
}
inline const std::string& KickAccountSessionAck::account_id() const {
  // @@protoc_insertion_point(field_get:pb.ipc.KickAccountSessionAck.account_id)
  return _internal_account_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void KickAccountSessionAck::set_account_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.account_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb.ipc.KickAccountSessionAck.account_id)
}
inline std::string* KickAccountSessionAck::mutable_account_id() {
  std::string* _s = _internal_mutable_account_id();
  // @@protoc_insertion_point(field_mutable:pb.ipc.KickAccountSessionAck.account_id)
  return _s;
}
inline const std::string& KickAccountSessionAck::_internal_account_id() const {
  return _impl_.account_id_.Get();
}
inline void KickAccountSessionAck::_internal_set_account_id(const std::string& value) {
  
  _impl_.account_id_.Set(value, GetArenaForAllocation());
}
inline std::string* KickAccountSessionAck::_internal_mutable_account_id() {
  
  return _impl_.account_id_.Mutable(GetArenaForAllocation());
}
inline std::string* KickAccountSessionAck::release_account_id() {
  // @@protoc_insertion_point(field_release:pb.ipc.KickAccountSessionAck.account_id)
  return _impl_.account_id_.Release();
}
inline void KickAccountSessionAck::set_allocated_account_id(std::string* account_id) {
  if (account_id != nullptr) {
    
  } else {
    
  }
  _impl_.account_id_.SetAllocated(account_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.account_id_.IsDefault()) {
    _impl_.account_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb.ipc.KickAccountSessionAck.account_id)
}

// uint64 old_gate_session_id = 4;
inline void KickAccountSessionAck::clear_old_gate_session_id() {
  _impl_.old_gate_session_id_ = uint64_t{0u};
}
inline uint64_t KickAccountSessionAck::_internal_old_gate_session_id() const {
  return _impl_.old_gate_session_id_;
}
inline uint64_t KickAccountSessionAck::old_gate_session_id() const {
  // @@protoc_insertion_point(field_get:pb.ipc.KickAccountSessionAck.old_gate_session_id)
  return _internal_old_gate_session_id();
}
inline void KickAccountSessionAck::_internal_set_old_gate_session_id(uint64_t value) {
  
  _impl_.old_gate_session_id_ = value;
}
inline void KickAccountSessionAck::set_old_gate_session_id(uint64_t value) {
  _internal_set_old_gate_session_id(value);
  // @@protoc_insertion_point(field_set:pb.ipc.KickAccountSessionAck.old_gate_session_id)
}

// -------------------------------------------------------------------

// PlayerDisconnected

// uint64 player_id = 1;
inline void PlayerDisconnected::clear_player_id() {
  _impl_.player_id_ = uint64_t{0u};
}
inline uint64_t PlayerDisconnected::_internal_player_id() const {
  return _impl_.player_id_;
}
inline uint64_t PlayerDisconnected::player_id() const {
  // @@protoc_insertion_point(field_get:pb.ipc.PlayerDisconnected.player_id)
  return _internal_player_id();
}
inline void PlayerDisconnected::_internal_set_player_id(uint64_t value) {
  
  _impl_.player_id_ = value;
}
inline void PlayerDisconnected::set_player_id(uint64_t value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:pb.ipc.PlayerDisconnected.player_id)
}

// uint32 gate_service_type = 2;
inline void PlayerDisconnected::clear_gate_service_type() {
  _impl_.gate_service_type_ = 0u;
}
inline uint32_t PlayerDisconnected::_internal_gate_service_type() const {
  return _impl_.gate_service_type_;
}
inline uint32_t PlayerDisconnected::gate_service_type() const {
  // @@protoc_insertion_point(field_get:pb.ipc.PlayerDisconnected.gate_service_type)
  return _internal_gate_service_type();
}
inline void PlayerDisconnected::_internal_set_gate_service_type(uint32_t value) {
  
  _impl_.gate_service_type_ = value;
}
inline void PlayerDisconnected::set_gate_service_type(uint32_t value) {
  _internal_set_gate_service_type(value);
  // @@protoc_insertion_point(field_set:pb.ipc.PlayerDisconnected.gate_service_type)
}

// uint32 gate_instance_id = 3;
inline void PlayerDisconnected::clear_gate_instance_id() {
  _impl_.gate_instance_id_ = 0u;
}
inline uint32_t PlayerDisconnected::_internal_gate_instance_id() const {
  return _impl_.gate_instance_id_;
}
inline uint32_t PlayerDisconnected::gate_instance_id() const {
  // @@protoc_insertion_point(field_get:pb.ipc.PlayerDisconnected.gate_instance_id)
  return _internal_gate_instance_id();
}
inline void PlayerDisconnected::_internal_set_gate_instance_id(uint32_t value) {
  
  _impl_.gate_instance_id_ = value;
}
inline void PlayerDisconnected::set_gate_instance_id(uint32_t value) {
  _internal_set_gate_instance_id(value);
  // @@protoc_insertion_point(field_set:pb.ipc.PlayerDisconnected.gate_instance_id)
}

// uint64 gate_session_id = 4;
inline void PlayerDisconnected::clear_gate_session_id() {
  _impl_.gate_session_id_ = uint64_t{0u};
}
inline uint64_t PlayerDisconnected::_internal_gate_session_id() const {
  return _impl_.gate_session_id_;
}
inline uint64_t PlayerDisconnected::gate_session_id() const {
  // @@protoc_insertion_point(field_get:pb.ipc.PlayerDisconnected.gate_session_id)
  return _internal_gate_session_id();
}
inline void PlayerDisconnected::_internal_set_gate_session_id(uint64_t value) {
  
  _impl_.gate_session_id_ = value;
}
inline void PlayerDisconnected::set_gate_session_id(uint64_t value) {
  _internal_set_gate_session_id(value);
  // @@protoc_insertion_point(field_set:pb.ipc.PlayerDisconnected.gate_session_id)
}

// .pb.ipc.DisconnectReason reason = 5;
inline void PlayerDisconnected::clear_reason() {
  _impl_.reason_ = 0;
}
inline ::pb::ipc::DisconnectReason PlayerDisconnected::_internal_reason() const {
  return static_cast< ::pb::ipc::DisconnectReason >(_impl_.reason_);
}
inline ::pb::ipc::DisconnectReason PlayerDisconnected::reason() const {
  // @@protoc_insertion_point(field_get:pb.ipc.PlayerDisconnected.reason)
  return _internal_reason();
}
inline void PlayerDisconnected::_internal_set_reason(::pb::ipc::DisconnectReason value) {
  
  _impl_.reason_ = value;
}
inline void PlayerDisconnected::set_reason(::pb::ipc::DisconnectReason value) {
  _internal_set_reason(value);
  // @@protoc_insertion_point(field_set:pb.ipc.PlayerDisconnected.reason)
}

// uint64 occurred_at_ms = 6;
inline void PlayerDisconnected::clear_occurred_at_ms() {
  _impl_.occurred_at_ms_ = uint64_t{0u};
}
inline uint64_t PlayerDisconnected::_internal_occurred_at_ms() const {
  return _impl_.occurred_at_ms_;
}
inline uint64_t PlayerDisconnected::occurred_at_ms() const {
  // @@protoc_insertion_point(field_get:pb.ipc.PlayerDisconnected.occurred_at_ms)
  return _internal_occurred_at_ms();
}
inline void PlayerDisconnected::_internal_set_occurred_at_ms(uint64_t value) {
  
  _impl_.occurred_at_ms_ = value;
}
inline void PlayerDisconnected::set_occurred_at_ms(uint64_t value) {
  _internal_set_occurred_at_ms(value);
  // @@protoc_insertion_point(field_set:pb.ipc.PlayerDisconnected.occurred_at_ms)
}

// -------------------------------------------------------------------

// BindPlayerSession

// uint64 player_id = 1;
inline void BindPlayerSession::clear_player_id() {
  _impl_.player_id_ = uint64_t{0u};
}
inline uint64_t BindPlayerSession::_internal_player_id() const {
  return _impl_.player_id_;
}
inline uint64_t BindPlayerSession::player_id() const {
  // @@protoc_insertion_point(field_get:pb.ipc.BindPlayerSession.player_id)
  return _internal_player_id();
}
inline void BindPlayerSession::_internal_set_player_id(uint64_t value) {
  
  _impl_.player_id_ = value;
}
inline void BindPlayerSession::set_player_id(uint64_t value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:pb.ipc.BindPlayerSession.player_id)
}

// uint32 gate_service_type = 2;
inline void BindPlayerSession::clear_gate_service_type() {
  _impl_.gate_service_type_ = 0u;
}
inline uint32_t BindPlayerSession::_internal_gate_service_type() const {
  return _impl_.gate_service_type_;
}
inline uint32_t BindPlayerSession::gate_service_type() const {
  // @@protoc_insertion_point(field_get:pb.ipc.BindPlayerSession.gate_service_type)
  return _internal_gate_service_type();
}
inline void BindPlayerSession::_internal_set_gate_service_type(uint32_t value) {
  
  _impl_.gate_service_type_ = value;
}
inline void BindPlayerSession::set_gate_service_type(uint32_t value) {
  _internal_set_gate_service_type(value);
  // @@protoc_insertion_point(field_set:pb.ipc.BindPlayerSession.gate_service_type)
}

// uint32 gate_instance_id = 3;
inline void BindPlayerSession::clear_gate_instance_id() {
  _impl_.gate_instance_id_ = 0u;
}
inline uint32_t BindPlayerSession::_internal_gate_instance_id() const {
  return _impl_.gate_instance_id_;
}
inline uint32_t BindPlayerSession::gate_instance_id() const {
  // @@protoc_insertion_point(field_get:pb.ipc.BindPlayerSession.gate_instance_id)
  return _internal_gate_instance_id();
}
inline void BindPlayerSession::_internal_set_gate_instance_id(uint32_t value) {
  
  _impl_.gate_instance_id_ = value;
}
inline void BindPlayerSession::set_gate_instance_id(uint32_t value) {
  _internal_set_gate_instance_id(value);
  // @@protoc_insertion_point(field_set:pb.ipc.BindPlayerSession.gate_instance_id)
}

// uint64 gate_session_id = 4;
inline void BindPlayerSession::clear_gate_session_id() {
  _impl_.gate_session_id_ = uint64_t{0u};
}
inline uint64_t BindPlayerSession::_internal_gate_session_id() const {
  return _impl_.gate_session_id_;
}
inline uint64_t BindPlayerSession::gate_session_id() const {
  // @@protoc_insertion_point(field_get:pb.ipc.BindPlayerSession.gate_session_id)
  return _internal_gate_session_id();
}
inline void BindPlayerSession::_internal_set_gate_session_id(uint64_t value) {
  
  _impl_.gate_session_id_ = value;
}
inline void BindPlayerSession::set_gate_session_id(uint64_t value) {
  _internal_set_gate_session_id(value);
  // @@protoc_insertion_point(field_set:pb.ipc.BindPlayerSession.gate_session_id)
}

// -------------------------------------------------------------------

// UnbindPlayerSession

// uint64 player_id = 1;
inline void UnbindPlayerSession::clear_player_id() {
  _impl_.player_id_ = uint64_t{0u};
}
inline uint64_t UnbindPlayerSession::_internal_player_id() const {
  return _impl_.player_id_;
}
inline uint64_t UnbindPlayerSession::player_id() const {
  // @@protoc_insertion_point(field_get:pb.ipc.UnbindPlayerSession.player_id)
  return _internal_player_id();
}
inline void UnbindPlayerSession::_internal_set_player_id(uint64_t value) {
  
  _impl_.player_id_ = value;
}
inline void UnbindPlayerSession::set_player_id(uint64_t value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:pb.ipc.UnbindPlayerSession.player_id)
}

// uint32 gate_service_type = 2;
inline void UnbindPlayerSession::clear_gate_service_type() {
  _impl_.gate_service_type_ = 0u;
}
inline uint32_t UnbindPlayerSession::_internal_gate_service_type() const {
  return _impl_.gate_service_type_;
}
inline uint32_t UnbindPlayerSession::gate_service_type() const {
  // @@protoc_insertion_point(field_get:pb.ipc.UnbindPlayerSession.gate_service_type)
  return _internal_gate_service_type();
}
inline void UnbindPlayerSession::_internal_set_gate_service_type(uint32_t value) {
  
  _impl_.gate_service_type_ = value;
}
inline void UnbindPlayerSession::set_gate_service_type(uint32_t value) {
  _internal_set_gate_service_type(value);
  // @@protoc_insertion_point(field_set:pb.ipc.UnbindPlayerSession.gate_service_type)
}

// uint32 gate_instance_id = 3;
inline void UnbindPlayerSession::clear_gate_instance_id() {
  _impl_.gate_instance_id_ = 0u;
}
inline uint32_t UnbindPlayerSession::_internal_gate_instance_id() const {
  return _impl_.gate_instance_id_;
}
inline uint32_t UnbindPlayerSession::gate_instance_id() const {
  // @@protoc_insertion_point(field_get:pb.ipc.UnbindPlayerSession.gate_instance_id)
  return _internal_gate_instance_id();
}
inline void UnbindPlayerSession::_internal_set_gate_instance_id(uint32_t value) {
  
  _impl_.gate_instance_id_ = value;
}
inline void UnbindPlayerSession::set_gate_instance_id(uint32_t value) {
  _internal_set_gate_instance_id(value);
  // @@protoc_insertion_point(field_set:pb.ipc.UnbindPlayerSession.gate_instance_id)
}

// uint64 gate_session_id = 4;
inline void UnbindPlayerSession::clear_gate_session_id() {
  _impl_.gate_session_id_ = uint64_t{0u};
}
inline uint64_t UnbindPlayerSession::_internal_gate_session_id() const {
  return _impl_.gate_session_id_;
}
inline uint64_t UnbindPlayerSession::gate_session_id() const {
  // @@protoc_insertion_point(field_get:pb.ipc.UnbindPlayerSession.gate_session_id)
  return _internal_gate_session_id();
}
inline void UnbindPlayerSession::_internal_set_gate_session_id(uint64_t value) {
  
  _impl_.gate_session_id_ = value;
}
inline void UnbindPlayerSession::set_gate_session_id(uint64_t value) {
  _internal_set_gate_session_id(value);
  // @@protoc_insertion_point(field_set:pb.ipc.UnbindPlayerSession.gate_session_id)
}

// .pb.ipc.DisconnectReason reason = 5;
inline void UnbindPlayerSession::clear_reason() {
  _impl_.reason_ = 0;
}
inline ::pb::ipc::DisconnectReason UnbindPlayerSession::_internal_reason() const {
  return static_cast< ::pb::ipc::DisconnectReason >(_impl_.reason_);
}
inline ::pb::ipc::DisconnectReason UnbindPlayerSession::reason() const {
  // @@protoc_insertion_point(field_get:pb.ipc.UnbindPlayerSession.reason)
  return _internal_reason();
}
inline void UnbindPlayerSession::_internal_set_reason(::pb::ipc::DisconnectReason value) {
  
  _impl_.reason_ = value;
}
inline void UnbindPlayerSession::set_reason(::pb::ipc::DisconnectReason value) {
  _internal_set_reason(value);
  // @@protoc_insertion_point(field_set:pb.ipc.UnbindPlayerSession.reason)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ipc
}  // namespace pb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ipc_2fsession_2eproto
