// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipc/gate_game/v1/common.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ipc_2fgate_5fgame_2fv1_2fcommon_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ipc_2fgate_5fgame_2fv1_2fcommon_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ipc_2fgate_5fgame_2fv1_2fcommon_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ipc_2fgate_5fgame_2fv1_2fcommon_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ipc_2fgate_5fgame_2fv1_2fcommon_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace some_server {
namespace ipc {
namespace gate_game {
namespace v1 {

enum ResultCode : int {
  RESULT_CODE_UNSPECIFIED = 0,
  RESULT_CODE_OK = 1,
  RESULT_CODE_INVALID_ARGUMENT = 2,
  RESULT_CODE_UNAUTHORIZED = 3,
  RESULT_CODE_PLAYER_NOT_FOUND = 4,
  RESULT_CODE_PLAYER_HELD_BY_OTHER_GAME = 5,
  RESULT_CODE_SESSION_EXPIRED = 6,
  RESULT_CODE_ROUTE_MISMATCH = 7,
  RESULT_CODE_INTERNAL = 8,
  ResultCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ResultCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ResultCode_IsValid(int value);
constexpr ResultCode ResultCode_MIN = RESULT_CODE_UNSPECIFIED;
constexpr ResultCode ResultCode_MAX = RESULT_CODE_INTERNAL;
constexpr int ResultCode_ARRAYSIZE = ResultCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ResultCode_descriptor();
template<typename T>
inline const std::string& ResultCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ResultCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ResultCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ResultCode_descriptor(), enum_t_value);
}
inline bool ResultCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ResultCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ResultCode>(
    ResultCode_descriptor(), name, value);
}
enum DisconnectReason : int {
  DISCONNECT_REASON_UNSPECIFIED = 0,
  DISCONNECT_REASON_CLIENT_CLOSED = 1,
  DISCONNECT_REASON_HEARTBEAT_TIMEOUT = 2,
  DISCONNECT_REASON_KICKED = 3,
  DISCONNECT_REASON_GATE_SHUTDOWN = 4,
  DisconnectReason_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  DisconnectReason_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool DisconnectReason_IsValid(int value);
constexpr DisconnectReason DisconnectReason_MIN = DISCONNECT_REASON_UNSPECIFIED;
constexpr DisconnectReason DisconnectReason_MAX = DISCONNECT_REASON_GATE_SHUTDOWN;
constexpr int DisconnectReason_ARRAYSIZE = DisconnectReason_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DisconnectReason_descriptor();
template<typename T>
inline const std::string& DisconnectReason_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DisconnectReason>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DisconnectReason_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DisconnectReason_descriptor(), enum_t_value);
}
inline bool DisconnectReason_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DisconnectReason* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DisconnectReason>(
    DisconnectReason_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace gate_game
}  // namespace ipc
}  // namespace some_server

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::some_server::ipc::gate_game::v1::ResultCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::some_server::ipc::gate_game::v1::ResultCode>() {
  return ::some_server::ipc::gate_game::v1::ResultCode_descriptor();
}
template <> struct is_proto_enum< ::some_server::ipc::gate_game::v1::DisconnectReason> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::some_server::ipc::gate_game::v1::DisconnectReason>() {
  return ::some_server::ipc::gate_game::v1::DisconnectReason_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ipc_2fgate_5fgame_2fv1_2fcommon_2eproto
