// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipc/gate_game/v1/session.proto

#include "ipc/gate_game/v1/session.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace some_server {
namespace ipc {
namespace gate_game {
namespace v1 {
PROTOBUF_CONSTEXPR KickAccountSession::KickAccountSession(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.account_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.reason_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.request_id_)*/uint64_t{0u}
  , /*decltype(_impl_.old_gate_service_type_)*/0u
  , /*decltype(_impl_.old_gate_instance_id_)*/0u
  , /*decltype(_impl_.old_gate_session_id_)*/uint64_t{0u}
  , /*decltype(_impl_.new_gate_service_type_)*/0u
  , /*decltype(_impl_.new_gate_instance_id_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct KickAccountSessionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR KickAccountSessionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~KickAccountSessionDefaultTypeInternal() {}
  union {
    KickAccountSession _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 KickAccountSessionDefaultTypeInternal _KickAccountSession_default_instance_;
PROTOBUF_CONSTEXPR KickAccountSessionAck::KickAccountSessionAck(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.account_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.request_id_)*/uint64_t{0u}
  , /*decltype(_impl_.old_gate_session_id_)*/uint64_t{0u}
  , /*decltype(_impl_.result_code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct KickAccountSessionAckDefaultTypeInternal {
  PROTOBUF_CONSTEXPR KickAccountSessionAckDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~KickAccountSessionAckDefaultTypeInternal() {}
  union {
    KickAccountSessionAck _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 KickAccountSessionAckDefaultTypeInternal _KickAccountSessionAck_default_instance_;
PROTOBUF_CONSTEXPR PlayerDisconnected::PlayerDisconnected(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.player_id_)*/uint64_t{0u}
  , /*decltype(_impl_.gate_service_type_)*/0u
  , /*decltype(_impl_.gate_instance_id_)*/0u
  , /*decltype(_impl_.gate_session_id_)*/uint64_t{0u}
  , /*decltype(_impl_.occurred_at_ms_)*/uint64_t{0u}
  , /*decltype(_impl_.reason_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PlayerDisconnectedDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerDisconnectedDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerDisconnectedDefaultTypeInternal() {}
  union {
    PlayerDisconnected _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerDisconnectedDefaultTypeInternal _PlayerDisconnected_default_instance_;
PROTOBUF_CONSTEXPR BindPlayerSession::BindPlayerSession(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.player_id_)*/uint64_t{0u}
  , /*decltype(_impl_.gate_service_type_)*/0u
  , /*decltype(_impl_.gate_instance_id_)*/0u
  , /*decltype(_impl_.gate_session_id_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BindPlayerSessionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BindPlayerSessionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BindPlayerSessionDefaultTypeInternal() {}
  union {
    BindPlayerSession _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BindPlayerSessionDefaultTypeInternal _BindPlayerSession_default_instance_;
PROTOBUF_CONSTEXPR UnbindPlayerSession::UnbindPlayerSession(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.player_id_)*/uint64_t{0u}
  , /*decltype(_impl_.gate_service_type_)*/0u
  , /*decltype(_impl_.gate_instance_id_)*/0u
  , /*decltype(_impl_.gate_session_id_)*/uint64_t{0u}
  , /*decltype(_impl_.reason_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UnbindPlayerSessionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UnbindPlayerSessionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UnbindPlayerSessionDefaultTypeInternal() {}
  union {
    UnbindPlayerSession _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UnbindPlayerSessionDefaultTypeInternal _UnbindPlayerSession_default_instance_;
}  // namespace v1
}  // namespace gate_game
}  // namespace ipc
}  // namespace some_server
static ::_pb::Metadata file_level_metadata_ipc_2fgate_5fgame_2fv1_2fsession_2eproto[5];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_ipc_2fgate_5fgame_2fv1_2fsession_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ipc_2fgate_5fgame_2fv1_2fsession_2eproto = nullptr;

const uint32_t TableStruct_ipc_2fgate_5fgame_2fv1_2fsession_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::KickAccountSession, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::KickAccountSession, _impl_.request_id_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::KickAccountSession, _impl_.account_id_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::KickAccountSession, _impl_.old_gate_service_type_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::KickAccountSession, _impl_.old_gate_instance_id_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::KickAccountSession, _impl_.old_gate_session_id_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::KickAccountSession, _impl_.new_gate_service_type_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::KickAccountSession, _impl_.new_gate_instance_id_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::KickAccountSession, _impl_.reason_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::KickAccountSessionAck, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::KickAccountSessionAck, _impl_.request_id_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::KickAccountSessionAck, _impl_.result_code_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::KickAccountSessionAck, _impl_.account_id_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::KickAccountSessionAck, _impl_.old_gate_session_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::PlayerDisconnected, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::PlayerDisconnected, _impl_.player_id_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::PlayerDisconnected, _impl_.gate_service_type_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::PlayerDisconnected, _impl_.gate_instance_id_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::PlayerDisconnected, _impl_.gate_session_id_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::PlayerDisconnected, _impl_.reason_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::PlayerDisconnected, _impl_.occurred_at_ms_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::BindPlayerSession, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::BindPlayerSession, _impl_.player_id_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::BindPlayerSession, _impl_.gate_service_type_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::BindPlayerSession, _impl_.gate_instance_id_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::BindPlayerSession, _impl_.gate_session_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::UnbindPlayerSession, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::UnbindPlayerSession, _impl_.player_id_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::UnbindPlayerSession, _impl_.gate_service_type_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::UnbindPlayerSession, _impl_.gate_instance_id_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::UnbindPlayerSession, _impl_.gate_session_id_),
  PROTOBUF_FIELD_OFFSET(::some_server::ipc::gate_game::v1::UnbindPlayerSession, _impl_.reason_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::some_server::ipc::gate_game::v1::KickAccountSession)},
  { 14, -1, -1, sizeof(::some_server::ipc::gate_game::v1::KickAccountSessionAck)},
  { 24, -1, -1, sizeof(::some_server::ipc::gate_game::v1::PlayerDisconnected)},
  { 36, -1, -1, sizeof(::some_server::ipc::gate_game::v1::BindPlayerSession)},
  { 46, -1, -1, sizeof(::some_server::ipc::gate_game::v1::UnbindPlayerSession)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::some_server::ipc::gate_game::v1::_KickAccountSession_default_instance_._instance,
  &::some_server::ipc::gate_game::v1::_KickAccountSessionAck_default_instance_._instance,
  &::some_server::ipc::gate_game::v1::_PlayerDisconnected_default_instance_._instance,
  &::some_server::ipc::gate_game::v1::_BindPlayerSession_default_instance_._instance,
  &::some_server::ipc::gate_game::v1::_UnbindPlayerSession_default_instance_._instance,
};

const char descriptor_table_protodef_ipc_2fgate_5fgame_2fv1_2fsession_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\036ipc/gate_game/v1/session.proto\022\034some_s"
  "erver.ipc.gate_game.v1\032\035ipc/gate_game/v1"
  "/common.proto\"\343\001\n\022KickAccountSession\022\022\n\n"
  "request_id\030\001 \001(\004\022\022\n\naccount_id\030\002 \001(\t\022\035\n\025"
  "old_gate_service_type\030\003 \001(\r\022\034\n\024old_gate_"
  "instance_id\030\004 \001(\r\022\033\n\023old_gate_session_id"
  "\030\005 \001(\004\022\035\n\025new_gate_service_type\030\006 \001(\r\022\034\n"
  "\024new_gate_instance_id\030\007 \001(\r\022\016\n\006reason\030\010 "
  "\001(\t\"\233\001\n\025KickAccountSessionAck\022\022\n\nrequest"
  "_id\030\001 \001(\004\022=\n\013result_code\030\002 \001(\0162(.some_se"
  "rver.ipc.gate_game.v1.ResultCode\022\022\n\nacco"
  "unt_id\030\003 \001(\t\022\033\n\023old_gate_session_id\030\004 \001("
  "\004\"\315\001\n\022PlayerDisconnected\022\021\n\tplayer_id\030\001 "
  "\001(\004\022\031\n\021gate_service_type\030\002 \001(\r\022\030\n\020gate_i"
  "nstance_id\030\003 \001(\r\022\027\n\017gate_session_id\030\004 \001("
  "\004\022>\n\006reason\030\005 \001(\0162..some_server.ipc.gate"
  "_game.v1.DisconnectReason\022\026\n\016occurred_at"
  "_ms\030\006 \001(\004\"t\n\021BindPlayerSession\022\021\n\tplayer"
  "_id\030\001 \001(\004\022\031\n\021gate_service_type\030\002 \001(\r\022\030\n\020"
  "gate_instance_id\030\003 \001(\r\022\027\n\017gate_session_i"
  "d\030\004 \001(\004\"\266\001\n\023UnbindPlayerSession\022\021\n\tplaye"
  "r_id\030\001 \001(\004\022\031\n\021gate_service_type\030\002 \001(\r\022\030\n"
  "\020gate_instance_id\030\003 \001(\r\022\027\n\017gate_session_"
  "id\030\004 \001(\004\022>\n\006reason\030\005 \001(\0162..some_server.i"
  "pc.gate_game.v1.DisconnectReasonb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_ipc_2fgate_5fgame_2fv1_2fsession_2eproto_deps[1] = {
  &::descriptor_table_ipc_2fgate_5fgame_2fv1_2fcommon_2eproto,
};
static ::_pbi::once_flag descriptor_table_ipc_2fgate_5fgame_2fv1_2fsession_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ipc_2fgate_5fgame_2fv1_2fsession_2eproto = {
    false, false, 1000, descriptor_table_protodef_ipc_2fgate_5fgame_2fv1_2fsession_2eproto,
    "ipc/gate_game/v1/session.proto",
    &descriptor_table_ipc_2fgate_5fgame_2fv1_2fsession_2eproto_once, descriptor_table_ipc_2fgate_5fgame_2fv1_2fsession_2eproto_deps, 1, 5,
    schemas, file_default_instances, TableStruct_ipc_2fgate_5fgame_2fv1_2fsession_2eproto::offsets,
    file_level_metadata_ipc_2fgate_5fgame_2fv1_2fsession_2eproto, file_level_enum_descriptors_ipc_2fgate_5fgame_2fv1_2fsession_2eproto,
    file_level_service_descriptors_ipc_2fgate_5fgame_2fv1_2fsession_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ipc_2fgate_5fgame_2fv1_2fsession_2eproto_getter() {
  return &descriptor_table_ipc_2fgate_5fgame_2fv1_2fsession_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ipc_2fgate_5fgame_2fv1_2fsession_2eproto(&descriptor_table_ipc_2fgate_5fgame_2fv1_2fsession_2eproto);
namespace some_server {
namespace ipc {
namespace gate_game {
namespace v1 {

// ===================================================================

class KickAccountSession::_Internal {
 public:
};

KickAccountSession::KickAccountSession(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:some_server.ipc.gate_game.v1.KickAccountSession)
}
KickAccountSession::KickAccountSession(const KickAccountSession& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  KickAccountSession* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.account_id_){}
    , decltype(_impl_.reason_){}
    , decltype(_impl_.request_id_){}
    , decltype(_impl_.old_gate_service_type_){}
    , decltype(_impl_.old_gate_instance_id_){}
    , decltype(_impl_.old_gate_session_id_){}
    , decltype(_impl_.new_gate_service_type_){}
    , decltype(_impl_.new_gate_instance_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.account_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.account_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_account_id().empty()) {
    _this->_impl_.account_id_.Set(from._internal_account_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.reason_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.reason_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_reason().empty()) {
    _this->_impl_.reason_.Set(from._internal_reason(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.request_id_, &from._impl_.request_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.new_gate_instance_id_) -
    reinterpret_cast<char*>(&_impl_.request_id_)) + sizeof(_impl_.new_gate_instance_id_));
  // @@protoc_insertion_point(copy_constructor:some_server.ipc.gate_game.v1.KickAccountSession)
}

inline void KickAccountSession::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.account_id_){}
    , decltype(_impl_.reason_){}
    , decltype(_impl_.request_id_){uint64_t{0u}}
    , decltype(_impl_.old_gate_service_type_){0u}
    , decltype(_impl_.old_gate_instance_id_){0u}
    , decltype(_impl_.old_gate_session_id_){uint64_t{0u}}
    , decltype(_impl_.new_gate_service_type_){0u}
    , decltype(_impl_.new_gate_instance_id_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.account_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.account_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.reason_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.reason_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

KickAccountSession::~KickAccountSession() {
  // @@protoc_insertion_point(destructor:some_server.ipc.gate_game.v1.KickAccountSession)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void KickAccountSession::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.account_id_.Destroy();
  _impl_.reason_.Destroy();
}

void KickAccountSession::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void KickAccountSession::Clear() {
// @@protoc_insertion_point(message_clear_start:some_server.ipc.gate_game.v1.KickAccountSession)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.account_id_.ClearToEmpty();
  _impl_.reason_.ClearToEmpty();
  ::memset(&_impl_.request_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.new_gate_instance_id_) -
      reinterpret_cast<char*>(&_impl_.request_id_)) + sizeof(_impl_.new_gate_instance_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* KickAccountSession::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 request_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.request_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string account_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_account_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "some_server.ipc.gate_game.v1.KickAccountSession.account_id"));
        } else
          goto handle_unusual;
        continue;
      // uint32 old_gate_service_type = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.old_gate_service_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 old_gate_instance_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.old_gate_instance_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 old_gate_session_id = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.old_gate_session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 new_gate_service_type = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.new_gate_service_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 new_gate_instance_id = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.new_gate_instance_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string reason = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_reason();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "some_server.ipc.gate_game.v1.KickAccountSession.reason"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* KickAccountSession::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:some_server.ipc.gate_game.v1.KickAccountSession)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 request_id = 1;
  if (this->_internal_request_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_request_id(), target);
  }

  // string account_id = 2;
  if (!this->_internal_account_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_account_id().data(), static_cast<int>(this->_internal_account_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "some_server.ipc.gate_game.v1.KickAccountSession.account_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_account_id(), target);
  }

  // uint32 old_gate_service_type = 3;
  if (this->_internal_old_gate_service_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_old_gate_service_type(), target);
  }

  // uint32 old_gate_instance_id = 4;
  if (this->_internal_old_gate_instance_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_old_gate_instance_id(), target);
  }

  // uint64 old_gate_session_id = 5;
  if (this->_internal_old_gate_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(5, this->_internal_old_gate_session_id(), target);
  }

  // uint32 new_gate_service_type = 6;
  if (this->_internal_new_gate_service_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(6, this->_internal_new_gate_service_type(), target);
  }

  // uint32 new_gate_instance_id = 7;
  if (this->_internal_new_gate_instance_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(7, this->_internal_new_gate_instance_id(), target);
  }

  // string reason = 8;
  if (!this->_internal_reason().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_reason().data(), static_cast<int>(this->_internal_reason().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "some_server.ipc.gate_game.v1.KickAccountSession.reason");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_reason(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:some_server.ipc.gate_game.v1.KickAccountSession)
  return target;
}

size_t KickAccountSession::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:some_server.ipc.gate_game.v1.KickAccountSession)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string account_id = 2;
  if (!this->_internal_account_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_account_id());
  }

  // string reason = 8;
  if (!this->_internal_reason().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_reason());
  }

  // uint64 request_id = 1;
  if (this->_internal_request_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_request_id());
  }

  // uint32 old_gate_service_type = 3;
  if (this->_internal_old_gate_service_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_old_gate_service_type());
  }

  // uint32 old_gate_instance_id = 4;
  if (this->_internal_old_gate_instance_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_old_gate_instance_id());
  }

  // uint64 old_gate_session_id = 5;
  if (this->_internal_old_gate_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_old_gate_session_id());
  }

  // uint32 new_gate_service_type = 6;
  if (this->_internal_new_gate_service_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_new_gate_service_type());
  }

  // uint32 new_gate_instance_id = 7;
  if (this->_internal_new_gate_instance_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_new_gate_instance_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData KickAccountSession::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    KickAccountSession::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*KickAccountSession::GetClassData() const { return &_class_data_; }


void KickAccountSession::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<KickAccountSession*>(&to_msg);
  auto& from = static_cast<const KickAccountSession&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:some_server.ipc.gate_game.v1.KickAccountSession)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_account_id().empty()) {
    _this->_internal_set_account_id(from._internal_account_id());
  }
  if (!from._internal_reason().empty()) {
    _this->_internal_set_reason(from._internal_reason());
  }
  if (from._internal_request_id() != 0) {
    _this->_internal_set_request_id(from._internal_request_id());
  }
  if (from._internal_old_gate_service_type() != 0) {
    _this->_internal_set_old_gate_service_type(from._internal_old_gate_service_type());
  }
  if (from._internal_old_gate_instance_id() != 0) {
    _this->_internal_set_old_gate_instance_id(from._internal_old_gate_instance_id());
  }
  if (from._internal_old_gate_session_id() != 0) {
    _this->_internal_set_old_gate_session_id(from._internal_old_gate_session_id());
  }
  if (from._internal_new_gate_service_type() != 0) {
    _this->_internal_set_new_gate_service_type(from._internal_new_gate_service_type());
  }
  if (from._internal_new_gate_instance_id() != 0) {
    _this->_internal_set_new_gate_instance_id(from._internal_new_gate_instance_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void KickAccountSession::CopyFrom(const KickAccountSession& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:some_server.ipc.gate_game.v1.KickAccountSession)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KickAccountSession::IsInitialized() const {
  return true;
}

void KickAccountSession::InternalSwap(KickAccountSession* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.account_id_, lhs_arena,
      &other->_impl_.account_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.reason_, lhs_arena,
      &other->_impl_.reason_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(KickAccountSession, _impl_.new_gate_instance_id_)
      + sizeof(KickAccountSession::_impl_.new_gate_instance_id_)
      - PROTOBUF_FIELD_OFFSET(KickAccountSession, _impl_.request_id_)>(
          reinterpret_cast<char*>(&_impl_.request_id_),
          reinterpret_cast<char*>(&other->_impl_.request_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata KickAccountSession::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ipc_2fgate_5fgame_2fv1_2fsession_2eproto_getter, &descriptor_table_ipc_2fgate_5fgame_2fv1_2fsession_2eproto_once,
      file_level_metadata_ipc_2fgate_5fgame_2fv1_2fsession_2eproto[0]);
}

// ===================================================================

class KickAccountSessionAck::_Internal {
 public:
};

KickAccountSessionAck::KickAccountSessionAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:some_server.ipc.gate_game.v1.KickAccountSessionAck)
}
KickAccountSessionAck::KickAccountSessionAck(const KickAccountSessionAck& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  KickAccountSessionAck* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.account_id_){}
    , decltype(_impl_.request_id_){}
    , decltype(_impl_.old_gate_session_id_){}
    , decltype(_impl_.result_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.account_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.account_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_account_id().empty()) {
    _this->_impl_.account_id_.Set(from._internal_account_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.request_id_, &from._impl_.request_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.result_code_) -
    reinterpret_cast<char*>(&_impl_.request_id_)) + sizeof(_impl_.result_code_));
  // @@protoc_insertion_point(copy_constructor:some_server.ipc.gate_game.v1.KickAccountSessionAck)
}

inline void KickAccountSessionAck::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.account_id_){}
    , decltype(_impl_.request_id_){uint64_t{0u}}
    , decltype(_impl_.old_gate_session_id_){uint64_t{0u}}
    , decltype(_impl_.result_code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.account_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.account_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

KickAccountSessionAck::~KickAccountSessionAck() {
  // @@protoc_insertion_point(destructor:some_server.ipc.gate_game.v1.KickAccountSessionAck)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void KickAccountSessionAck::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.account_id_.Destroy();
}

void KickAccountSessionAck::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void KickAccountSessionAck::Clear() {
// @@protoc_insertion_point(message_clear_start:some_server.ipc.gate_game.v1.KickAccountSessionAck)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.account_id_.ClearToEmpty();
  ::memset(&_impl_.request_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.result_code_) -
      reinterpret_cast<char*>(&_impl_.request_id_)) + sizeof(_impl_.result_code_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* KickAccountSessionAck::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 request_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.request_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .some_server.ipc.gate_game.v1.ResultCode result_code = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_result_code(static_cast<::some_server::ipc::gate_game::v1::ResultCode>(val));
        } else
          goto handle_unusual;
        continue;
      // string account_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_account_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "some_server.ipc.gate_game.v1.KickAccountSessionAck.account_id"));
        } else
          goto handle_unusual;
        continue;
      // uint64 old_gate_session_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.old_gate_session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* KickAccountSessionAck::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:some_server.ipc.gate_game.v1.KickAccountSessionAck)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 request_id = 1;
  if (this->_internal_request_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_request_id(), target);
  }

  // .some_server.ipc.gate_game.v1.ResultCode result_code = 2;
  if (this->_internal_result_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_result_code(), target);
  }

  // string account_id = 3;
  if (!this->_internal_account_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_account_id().data(), static_cast<int>(this->_internal_account_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "some_server.ipc.gate_game.v1.KickAccountSessionAck.account_id");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_account_id(), target);
  }

  // uint64 old_gate_session_id = 4;
  if (this->_internal_old_gate_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(4, this->_internal_old_gate_session_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:some_server.ipc.gate_game.v1.KickAccountSessionAck)
  return target;
}

size_t KickAccountSessionAck::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:some_server.ipc.gate_game.v1.KickAccountSessionAck)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string account_id = 3;
  if (!this->_internal_account_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_account_id());
  }

  // uint64 request_id = 1;
  if (this->_internal_request_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_request_id());
  }

  // uint64 old_gate_session_id = 4;
  if (this->_internal_old_gate_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_old_gate_session_id());
  }

  // .some_server.ipc.gate_game.v1.ResultCode result_code = 2;
  if (this->_internal_result_code() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_result_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData KickAccountSessionAck::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    KickAccountSessionAck::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*KickAccountSessionAck::GetClassData() const { return &_class_data_; }


void KickAccountSessionAck::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<KickAccountSessionAck*>(&to_msg);
  auto& from = static_cast<const KickAccountSessionAck&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:some_server.ipc.gate_game.v1.KickAccountSessionAck)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_account_id().empty()) {
    _this->_internal_set_account_id(from._internal_account_id());
  }
  if (from._internal_request_id() != 0) {
    _this->_internal_set_request_id(from._internal_request_id());
  }
  if (from._internal_old_gate_session_id() != 0) {
    _this->_internal_set_old_gate_session_id(from._internal_old_gate_session_id());
  }
  if (from._internal_result_code() != 0) {
    _this->_internal_set_result_code(from._internal_result_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void KickAccountSessionAck::CopyFrom(const KickAccountSessionAck& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:some_server.ipc.gate_game.v1.KickAccountSessionAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KickAccountSessionAck::IsInitialized() const {
  return true;
}

void KickAccountSessionAck::InternalSwap(KickAccountSessionAck* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.account_id_, lhs_arena,
      &other->_impl_.account_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(KickAccountSessionAck, _impl_.result_code_)
      + sizeof(KickAccountSessionAck::_impl_.result_code_)
      - PROTOBUF_FIELD_OFFSET(KickAccountSessionAck, _impl_.request_id_)>(
          reinterpret_cast<char*>(&_impl_.request_id_),
          reinterpret_cast<char*>(&other->_impl_.request_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata KickAccountSessionAck::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ipc_2fgate_5fgame_2fv1_2fsession_2eproto_getter, &descriptor_table_ipc_2fgate_5fgame_2fv1_2fsession_2eproto_once,
      file_level_metadata_ipc_2fgate_5fgame_2fv1_2fsession_2eproto[1]);
}

// ===================================================================

class PlayerDisconnected::_Internal {
 public:
};

PlayerDisconnected::PlayerDisconnected(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:some_server.ipc.gate_game.v1.PlayerDisconnected)
}
PlayerDisconnected::PlayerDisconnected(const PlayerDisconnected& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PlayerDisconnected* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.player_id_){}
    , decltype(_impl_.gate_service_type_){}
    , decltype(_impl_.gate_instance_id_){}
    , decltype(_impl_.gate_session_id_){}
    , decltype(_impl_.occurred_at_ms_){}
    , decltype(_impl_.reason_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.player_id_, &from._impl_.player_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.reason_) -
    reinterpret_cast<char*>(&_impl_.player_id_)) + sizeof(_impl_.reason_));
  // @@protoc_insertion_point(copy_constructor:some_server.ipc.gate_game.v1.PlayerDisconnected)
}

inline void PlayerDisconnected::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.player_id_){uint64_t{0u}}
    , decltype(_impl_.gate_service_type_){0u}
    , decltype(_impl_.gate_instance_id_){0u}
    , decltype(_impl_.gate_session_id_){uint64_t{0u}}
    , decltype(_impl_.occurred_at_ms_){uint64_t{0u}}
    , decltype(_impl_.reason_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PlayerDisconnected::~PlayerDisconnected() {
  // @@protoc_insertion_point(destructor:some_server.ipc.gate_game.v1.PlayerDisconnected)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PlayerDisconnected::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PlayerDisconnected::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PlayerDisconnected::Clear() {
// @@protoc_insertion_point(message_clear_start:some_server.ipc.gate_game.v1.PlayerDisconnected)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.player_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.reason_) -
      reinterpret_cast<char*>(&_impl_.player_id_)) + sizeof(_impl_.reason_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerDisconnected::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 player_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.player_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 gate_service_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.gate_service_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 gate_instance_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.gate_instance_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 gate_session_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.gate_session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .some_server.ipc.gate_game.v1.DisconnectReason reason = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_reason(static_cast<::some_server::ipc::gate_game::v1::DisconnectReason>(val));
        } else
          goto handle_unusual;
        continue;
      // uint64 occurred_at_ms = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.occurred_at_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlayerDisconnected::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:some_server.ipc.gate_game.v1.PlayerDisconnected)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 player_id = 1;
  if (this->_internal_player_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_player_id(), target);
  }

  // uint32 gate_service_type = 2;
  if (this->_internal_gate_service_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_gate_service_type(), target);
  }

  // uint32 gate_instance_id = 3;
  if (this->_internal_gate_instance_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_gate_instance_id(), target);
  }

  // uint64 gate_session_id = 4;
  if (this->_internal_gate_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(4, this->_internal_gate_session_id(), target);
  }

  // .some_server.ipc.gate_game.v1.DisconnectReason reason = 5;
  if (this->_internal_reason() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      5, this->_internal_reason(), target);
  }

  // uint64 occurred_at_ms = 6;
  if (this->_internal_occurred_at_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(6, this->_internal_occurred_at_ms(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:some_server.ipc.gate_game.v1.PlayerDisconnected)
  return target;
}

size_t PlayerDisconnected::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:some_server.ipc.gate_game.v1.PlayerDisconnected)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 player_id = 1;
  if (this->_internal_player_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_player_id());
  }

  // uint32 gate_service_type = 2;
  if (this->_internal_gate_service_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_gate_service_type());
  }

  // uint32 gate_instance_id = 3;
  if (this->_internal_gate_instance_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_gate_instance_id());
  }

  // uint64 gate_session_id = 4;
  if (this->_internal_gate_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_gate_session_id());
  }

  // uint64 occurred_at_ms = 6;
  if (this->_internal_occurred_at_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_occurred_at_ms());
  }

  // .some_server.ipc.gate_game.v1.DisconnectReason reason = 5;
  if (this->_internal_reason() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_reason());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerDisconnected::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PlayerDisconnected::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerDisconnected::GetClassData() const { return &_class_data_; }


void PlayerDisconnected::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PlayerDisconnected*>(&to_msg);
  auto& from = static_cast<const PlayerDisconnected&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:some_server.ipc.gate_game.v1.PlayerDisconnected)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_player_id() != 0) {
    _this->_internal_set_player_id(from._internal_player_id());
  }
  if (from._internal_gate_service_type() != 0) {
    _this->_internal_set_gate_service_type(from._internal_gate_service_type());
  }
  if (from._internal_gate_instance_id() != 0) {
    _this->_internal_set_gate_instance_id(from._internal_gate_instance_id());
  }
  if (from._internal_gate_session_id() != 0) {
    _this->_internal_set_gate_session_id(from._internal_gate_session_id());
  }
  if (from._internal_occurred_at_ms() != 0) {
    _this->_internal_set_occurred_at_ms(from._internal_occurred_at_ms());
  }
  if (from._internal_reason() != 0) {
    _this->_internal_set_reason(from._internal_reason());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerDisconnected::CopyFrom(const PlayerDisconnected& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:some_server.ipc.gate_game.v1.PlayerDisconnected)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerDisconnected::IsInitialized() const {
  return true;
}

void PlayerDisconnected::InternalSwap(PlayerDisconnected* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerDisconnected, _impl_.reason_)
      + sizeof(PlayerDisconnected::_impl_.reason_)
      - PROTOBUF_FIELD_OFFSET(PlayerDisconnected, _impl_.player_id_)>(
          reinterpret_cast<char*>(&_impl_.player_id_),
          reinterpret_cast<char*>(&other->_impl_.player_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerDisconnected::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ipc_2fgate_5fgame_2fv1_2fsession_2eproto_getter, &descriptor_table_ipc_2fgate_5fgame_2fv1_2fsession_2eproto_once,
      file_level_metadata_ipc_2fgate_5fgame_2fv1_2fsession_2eproto[2]);
}

// ===================================================================

class BindPlayerSession::_Internal {
 public:
};

BindPlayerSession::BindPlayerSession(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:some_server.ipc.gate_game.v1.BindPlayerSession)
}
BindPlayerSession::BindPlayerSession(const BindPlayerSession& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BindPlayerSession* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.player_id_){}
    , decltype(_impl_.gate_service_type_){}
    , decltype(_impl_.gate_instance_id_){}
    , decltype(_impl_.gate_session_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.player_id_, &from._impl_.player_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.gate_session_id_) -
    reinterpret_cast<char*>(&_impl_.player_id_)) + sizeof(_impl_.gate_session_id_));
  // @@protoc_insertion_point(copy_constructor:some_server.ipc.gate_game.v1.BindPlayerSession)
}

inline void BindPlayerSession::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.player_id_){uint64_t{0u}}
    , decltype(_impl_.gate_service_type_){0u}
    , decltype(_impl_.gate_instance_id_){0u}
    , decltype(_impl_.gate_session_id_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BindPlayerSession::~BindPlayerSession() {
  // @@protoc_insertion_point(destructor:some_server.ipc.gate_game.v1.BindPlayerSession)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BindPlayerSession::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void BindPlayerSession::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BindPlayerSession::Clear() {
// @@protoc_insertion_point(message_clear_start:some_server.ipc.gate_game.v1.BindPlayerSession)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.player_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.gate_session_id_) -
      reinterpret_cast<char*>(&_impl_.player_id_)) + sizeof(_impl_.gate_session_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BindPlayerSession::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 player_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.player_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 gate_service_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.gate_service_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 gate_instance_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.gate_instance_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 gate_session_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.gate_session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BindPlayerSession::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:some_server.ipc.gate_game.v1.BindPlayerSession)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 player_id = 1;
  if (this->_internal_player_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_player_id(), target);
  }

  // uint32 gate_service_type = 2;
  if (this->_internal_gate_service_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_gate_service_type(), target);
  }

  // uint32 gate_instance_id = 3;
  if (this->_internal_gate_instance_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_gate_instance_id(), target);
  }

  // uint64 gate_session_id = 4;
  if (this->_internal_gate_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(4, this->_internal_gate_session_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:some_server.ipc.gate_game.v1.BindPlayerSession)
  return target;
}

size_t BindPlayerSession::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:some_server.ipc.gate_game.v1.BindPlayerSession)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 player_id = 1;
  if (this->_internal_player_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_player_id());
  }

  // uint32 gate_service_type = 2;
  if (this->_internal_gate_service_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_gate_service_type());
  }

  // uint32 gate_instance_id = 3;
  if (this->_internal_gate_instance_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_gate_instance_id());
  }

  // uint64 gate_session_id = 4;
  if (this->_internal_gate_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_gate_session_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BindPlayerSession::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BindPlayerSession::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BindPlayerSession::GetClassData() const { return &_class_data_; }


void BindPlayerSession::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BindPlayerSession*>(&to_msg);
  auto& from = static_cast<const BindPlayerSession&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:some_server.ipc.gate_game.v1.BindPlayerSession)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_player_id() != 0) {
    _this->_internal_set_player_id(from._internal_player_id());
  }
  if (from._internal_gate_service_type() != 0) {
    _this->_internal_set_gate_service_type(from._internal_gate_service_type());
  }
  if (from._internal_gate_instance_id() != 0) {
    _this->_internal_set_gate_instance_id(from._internal_gate_instance_id());
  }
  if (from._internal_gate_session_id() != 0) {
    _this->_internal_set_gate_session_id(from._internal_gate_session_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BindPlayerSession::CopyFrom(const BindPlayerSession& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:some_server.ipc.gate_game.v1.BindPlayerSession)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BindPlayerSession::IsInitialized() const {
  return true;
}

void BindPlayerSession::InternalSwap(BindPlayerSession* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BindPlayerSession, _impl_.gate_session_id_)
      + sizeof(BindPlayerSession::_impl_.gate_session_id_)
      - PROTOBUF_FIELD_OFFSET(BindPlayerSession, _impl_.player_id_)>(
          reinterpret_cast<char*>(&_impl_.player_id_),
          reinterpret_cast<char*>(&other->_impl_.player_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata BindPlayerSession::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ipc_2fgate_5fgame_2fv1_2fsession_2eproto_getter, &descriptor_table_ipc_2fgate_5fgame_2fv1_2fsession_2eproto_once,
      file_level_metadata_ipc_2fgate_5fgame_2fv1_2fsession_2eproto[3]);
}

// ===================================================================

class UnbindPlayerSession::_Internal {
 public:
};

UnbindPlayerSession::UnbindPlayerSession(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:some_server.ipc.gate_game.v1.UnbindPlayerSession)
}
UnbindPlayerSession::UnbindPlayerSession(const UnbindPlayerSession& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UnbindPlayerSession* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.player_id_){}
    , decltype(_impl_.gate_service_type_){}
    , decltype(_impl_.gate_instance_id_){}
    , decltype(_impl_.gate_session_id_){}
    , decltype(_impl_.reason_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.player_id_, &from._impl_.player_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.reason_) -
    reinterpret_cast<char*>(&_impl_.player_id_)) + sizeof(_impl_.reason_));
  // @@protoc_insertion_point(copy_constructor:some_server.ipc.gate_game.v1.UnbindPlayerSession)
}

inline void UnbindPlayerSession::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.player_id_){uint64_t{0u}}
    , decltype(_impl_.gate_service_type_){0u}
    , decltype(_impl_.gate_instance_id_){0u}
    , decltype(_impl_.gate_session_id_){uint64_t{0u}}
    , decltype(_impl_.reason_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

UnbindPlayerSession::~UnbindPlayerSession() {
  // @@protoc_insertion_point(destructor:some_server.ipc.gate_game.v1.UnbindPlayerSession)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UnbindPlayerSession::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void UnbindPlayerSession::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UnbindPlayerSession::Clear() {
// @@protoc_insertion_point(message_clear_start:some_server.ipc.gate_game.v1.UnbindPlayerSession)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.player_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.reason_) -
      reinterpret_cast<char*>(&_impl_.player_id_)) + sizeof(_impl_.reason_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UnbindPlayerSession::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 player_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.player_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 gate_service_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.gate_service_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 gate_instance_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.gate_instance_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 gate_session_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.gate_session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .some_server.ipc.gate_game.v1.DisconnectReason reason = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_reason(static_cast<::some_server::ipc::gate_game::v1::DisconnectReason>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UnbindPlayerSession::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:some_server.ipc.gate_game.v1.UnbindPlayerSession)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 player_id = 1;
  if (this->_internal_player_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_player_id(), target);
  }

  // uint32 gate_service_type = 2;
  if (this->_internal_gate_service_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_gate_service_type(), target);
  }

  // uint32 gate_instance_id = 3;
  if (this->_internal_gate_instance_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_gate_instance_id(), target);
  }

  // uint64 gate_session_id = 4;
  if (this->_internal_gate_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(4, this->_internal_gate_session_id(), target);
  }

  // .some_server.ipc.gate_game.v1.DisconnectReason reason = 5;
  if (this->_internal_reason() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      5, this->_internal_reason(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:some_server.ipc.gate_game.v1.UnbindPlayerSession)
  return target;
}

size_t UnbindPlayerSession::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:some_server.ipc.gate_game.v1.UnbindPlayerSession)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 player_id = 1;
  if (this->_internal_player_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_player_id());
  }

  // uint32 gate_service_type = 2;
  if (this->_internal_gate_service_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_gate_service_type());
  }

  // uint32 gate_instance_id = 3;
  if (this->_internal_gate_instance_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_gate_instance_id());
  }

  // uint64 gate_session_id = 4;
  if (this->_internal_gate_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_gate_session_id());
  }

  // .some_server.ipc.gate_game.v1.DisconnectReason reason = 5;
  if (this->_internal_reason() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_reason());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UnbindPlayerSession::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UnbindPlayerSession::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UnbindPlayerSession::GetClassData() const { return &_class_data_; }


void UnbindPlayerSession::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UnbindPlayerSession*>(&to_msg);
  auto& from = static_cast<const UnbindPlayerSession&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:some_server.ipc.gate_game.v1.UnbindPlayerSession)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_player_id() != 0) {
    _this->_internal_set_player_id(from._internal_player_id());
  }
  if (from._internal_gate_service_type() != 0) {
    _this->_internal_set_gate_service_type(from._internal_gate_service_type());
  }
  if (from._internal_gate_instance_id() != 0) {
    _this->_internal_set_gate_instance_id(from._internal_gate_instance_id());
  }
  if (from._internal_gate_session_id() != 0) {
    _this->_internal_set_gate_session_id(from._internal_gate_session_id());
  }
  if (from._internal_reason() != 0) {
    _this->_internal_set_reason(from._internal_reason());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UnbindPlayerSession::CopyFrom(const UnbindPlayerSession& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:some_server.ipc.gate_game.v1.UnbindPlayerSession)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UnbindPlayerSession::IsInitialized() const {
  return true;
}

void UnbindPlayerSession::InternalSwap(UnbindPlayerSession* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UnbindPlayerSession, _impl_.reason_)
      + sizeof(UnbindPlayerSession::_impl_.reason_)
      - PROTOBUF_FIELD_OFFSET(UnbindPlayerSession, _impl_.player_id_)>(
          reinterpret_cast<char*>(&_impl_.player_id_),
          reinterpret_cast<char*>(&other->_impl_.player_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UnbindPlayerSession::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ipc_2fgate_5fgame_2fv1_2fsession_2eproto_getter, &descriptor_table_ipc_2fgate_5fgame_2fv1_2fsession_2eproto_once,
      file_level_metadata_ipc_2fgate_5fgame_2fv1_2fsession_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace gate_game
}  // namespace ipc
}  // namespace some_server
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::some_server::ipc::gate_game::v1::KickAccountSession*
Arena::CreateMaybeMessage< ::some_server::ipc::gate_game::v1::KickAccountSession >(Arena* arena) {
  return Arena::CreateMessageInternal< ::some_server::ipc::gate_game::v1::KickAccountSession >(arena);
}
template<> PROTOBUF_NOINLINE ::some_server::ipc::gate_game::v1::KickAccountSessionAck*
Arena::CreateMaybeMessage< ::some_server::ipc::gate_game::v1::KickAccountSessionAck >(Arena* arena) {
  return Arena::CreateMessageInternal< ::some_server::ipc::gate_game::v1::KickAccountSessionAck >(arena);
}
template<> PROTOBUF_NOINLINE ::some_server::ipc::gate_game::v1::PlayerDisconnected*
Arena::CreateMaybeMessage< ::some_server::ipc::gate_game::v1::PlayerDisconnected >(Arena* arena) {
  return Arena::CreateMessageInternal< ::some_server::ipc::gate_game::v1::PlayerDisconnected >(arena);
}
template<> PROTOBUF_NOINLINE ::some_server::ipc::gate_game::v1::BindPlayerSession*
Arena::CreateMaybeMessage< ::some_server::ipc::gate_game::v1::BindPlayerSession >(Arena* arena) {
  return Arena::CreateMessageInternal< ::some_server::ipc::gate_game::v1::BindPlayerSession >(arena);
}
template<> PROTOBUF_NOINLINE ::some_server::ipc::gate_game::v1::UnbindPlayerSession*
Arena::CreateMaybeMessage< ::some_server::ipc::gate_game::v1::UnbindPlayerSession >(Arena* arena) {
  return Arena::CreateMessageInternal< ::some_server::ipc::gate_game::v1::UnbindPlayerSession >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
