syntax = "proto3";

package pb;

enum MessageId {
  MESSAGE_ID_UNSPECIFIED = 0;

  MESSAGE_ID_LOGIN_REQUEST = 1001;
  MESSAGE_ID_HEARTBEAT_REQUEST = 1002;

  MESSAGE_ID_LOGIN_RESPONSE = 2001;
  MESSAGE_ID_HEARTBEAT_RESPONSE = 2002;
  MESSAGE_ID_KICK_NOTIFICATION = 2003;

  MESSAGE_ID_PLAYER_MESSAGE_REQUEST = 3001;
  MESSAGE_ID_PLAYER_MESSAGE_RESPONSE = 3002;
  MESSAGE_ID_PLAYER_PUSH = 3003;

  MESSAGE_ID_PLAYER_ECHO_REQUEST = 3101;
  MESSAGE_ID_PLAYER_RENAME_REQUEST = 3102;

  MESSAGE_ID_PLAYER_PROFILE_PUSH = 5101;
}
