some_add_source(pch.h)
some_add_source(main.cpp)
some_add_source(application.h)
some_add_source(application.cpp)
some_add_source(services/runtime_command_service.h)
some_add_source(services/runtime_command_service.cpp)
some_add_source(services/listener_service.h)
some_add_source(services/listener_service.cpp)
