some_add_source(pch.h)
some_add_source(application/application.h)
some_add_source(application/application.cpp)
some_add_source(application/lifecycle_task.h)
some_add_source(application/runtime.h)
some_add_source(application/service.h)
some_add_source(application/service_base.h)
some_add_source(storage/configuration.h)
some_add_source(storage/connectivity_probe.h)
some_add_source(storage/connectivity_probe.cpp)
some_add_source(storage/resolved_configuration.h)
some_add_source(storage/resolved_configuration.cpp)
some_add_source(storage/service.h)
some_add_source(storage/service.cpp)

set(IPC_SOURCE_PREFIX "ipc/")
include(ipc/ipc.cmake)
