some_add_source(pch.h)
some_add_source(application/application.h)
some_add_source(application/application.cpp)
some_add_source(application/lifecycle_task.h)
some_add_source(application/runtime.h)
some_add_source(application/service.h)
some_add_source(application/service_base.h)
