// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_ids.proto

#include "message_ids.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace pb {
}  // namespace pb
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_message_5fids_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_message_5fids_2eproto = nullptr;
const uint32_t TableStruct_message_5fids_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_message_5fids_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021message_ids.proto\022\002pb*\257\003\n\tMessageId\022\032\n"
  "\026MESSAGE_ID_UNSPECIFIED\020\000\022\035\n\030MESSAGE_ID_"
  "LOGIN_REQUEST\020\351\007\022!\n\034MESSAGE_ID_HEARTBEAT"
  "_REQUEST\020\352\007\022\036\n\031MESSAGE_ID_LOGIN_RESPONSE"
  "\020\321\017\022\"\n\035MESSAGE_ID_HEARTBEAT_RESPONSE\020\322\017\022"
  "!\n\034MESSAGE_ID_KICK_NOTIFICATION\020\323\017\022&\n!ME"
  "SSAGE_ID_PLAYER_MESSAGE_REQUEST\020\271\027\022\'\n\"ME"
  "SSAGE_ID_PLAYER_MESSAGE_RESPONSE\020\272\027\022\033\n\026M"
  "ESSAGE_ID_PLAYER_PUSH\020\273\027\022#\n\036MESSAGE_ID_P"
  "LAYER_ECHO_REQUEST\020\235\030\022%\n MESSAGE_ID_PLAY"
  "ER_RENAME_REQUEST\020\236\030\022#\n\036MESSAGE_ID_PLAYE"
  "R_PROFILE_PUSH\020\355\'b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_message_5fids_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_message_5fids_2eproto = {
    false, false, 465, descriptor_table_protodef_message_5fids_2eproto,
    "message_ids.proto",
    &descriptor_table_message_5fids_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_message_5fids_2eproto::offsets,
    nullptr, file_level_enum_descriptors_message_5fids_2eproto,
    file_level_service_descriptors_message_5fids_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_message_5fids_2eproto_getter() {
  return &descriptor_table_message_5fids_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_message_5fids_2eproto(&descriptor_table_message_5fids_2eproto);
namespace pb {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageId_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_message_5fids_2eproto);
  return file_level_enum_descriptors_message_5fids_2eproto[0];
}
bool MessageId_IsValid(int value) {
  switch (value) {
    case 0:
    case 1001:
    case 1002:
    case 2001:
    case 2002:
    case 2003:
    case 3001:
    case 3002:
    case 3003:
    case 3101:
    case 3102:
    case 5101:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
