// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player_data.proto

#include "player_data.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace pb {
PROTOBUF_CONSTEXPR PlayerBaseData::PlayerBaseData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.display_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.player_id_)*/uint64_t{0u}
  , /*decltype(_impl_.created_at_ms_)*/uint64_t{0u}
  , /*decltype(_impl_.last_login_at_ms_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PlayerBaseDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerBaseDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerBaseDataDefaultTypeInternal() {}
  union {
    PlayerBaseData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerBaseDataDefaultTypeInternal _PlayerBaseData_default_instance_;
PROTOBUF_CONSTEXPR PlayerCoreData::PlayerCoreData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.experience_)*/uint64_t{0u}
  , /*decltype(_impl_.login_count_)*/uint64_t{0u}
  , /*decltype(_impl_.level_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PlayerCoreDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerCoreDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerCoreDataDefaultTypeInternal() {}
  union {
    PlayerCoreData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerCoreDataDefaultTypeInternal _PlayerCoreData_default_instance_;
PROTOBUF_CONSTEXPR PlayerExtensionsData::PlayerExtensionsData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.opaque_blob_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PlayerExtensionsDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerExtensionsDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerExtensionsDataDefaultTypeInternal() {}
  union {
    PlayerExtensionsData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerExtensionsDataDefaultTypeInternal _PlayerExtensionsData_default_instance_;
PROTOBUF_CONSTEXPR PlayerData::PlayerData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.base_)*/nullptr
  , /*decltype(_impl_.core_)*/nullptr
  , /*decltype(_impl_.extensions_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PlayerDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerDataDefaultTypeInternal() {}
  union {
    PlayerData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerDataDefaultTypeInternal _PlayerData_default_instance_;
}  // namespace pb
static ::_pb::Metadata file_level_metadata_player_5fdata_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_player_5fdata_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_player_5fdata_2eproto = nullptr;

const uint32_t TableStruct_player_5fdata_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pb::PlayerBaseData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::pb::PlayerBaseData, _impl_.player_id_),
  PROTOBUF_FIELD_OFFSET(::pb::PlayerBaseData, _impl_.display_name_),
  PROTOBUF_FIELD_OFFSET(::pb::PlayerBaseData, _impl_.created_at_ms_),
  PROTOBUF_FIELD_OFFSET(::pb::PlayerBaseData, _impl_.last_login_at_ms_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pb::PlayerCoreData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::pb::PlayerCoreData, _impl_.level_),
  PROTOBUF_FIELD_OFFSET(::pb::PlayerCoreData, _impl_.experience_),
  PROTOBUF_FIELD_OFFSET(::pb::PlayerCoreData, _impl_.login_count_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pb::PlayerExtensionsData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::pb::PlayerExtensionsData, _impl_.opaque_blob_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pb::PlayerData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::pb::PlayerData, _impl_.base_),
  PROTOBUF_FIELD_OFFSET(::pb::PlayerData, _impl_.core_),
  PROTOBUF_FIELD_OFFSET(::pb::PlayerData, _impl_.extensions_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::pb::PlayerBaseData)},
  { 10, -1, -1, sizeof(::pb::PlayerCoreData)},
  { 19, -1, -1, sizeof(::pb::PlayerExtensionsData)},
  { 26, -1, -1, sizeof(::pb::PlayerData)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::pb::_PlayerBaseData_default_instance_._instance,
  &::pb::_PlayerCoreData_default_instance_._instance,
  &::pb::_PlayerExtensionsData_default_instance_._instance,
  &::pb::_PlayerData_default_instance_._instance,
};

const char descriptor_table_protodef_player_5fdata_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021player_data.proto\022\002pb\"j\n\016PlayerBaseDat"
  "a\022\021\n\tplayer_id\030\001 \001(\004\022\024\n\014display_name\030\002 \001"
  "(\t\022\025\n\rcreated_at_ms\030\003 \001(\004\022\030\n\020last_login_"
  "at_ms\030\004 \001(\004\"H\n\016PlayerCoreData\022\r\n\005level\030\001"
  " \001(\r\022\022\n\nexperience\030\002 \001(\004\022\023\n\013login_count\030"
  "\003 \001(\004\"+\n\024PlayerExtensionsData\022\023\n\013opaque_"
  "blob\030\001 \001(\014\"~\n\nPlayerData\022 \n\004base\030\001 \001(\0132\022"
  ".pb.PlayerBaseData\022 \n\004core\030\002 \001(\0132\022.pb.Pl"
  "ayerCoreData\022,\n\nextensions\030\003 \001(\0132\030.pb.Pl"
  "ayerExtensionsDatab\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_player_5fdata_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_player_5fdata_2eproto = {
    false, false, 386, descriptor_table_protodef_player_5fdata_2eproto,
    "player_data.proto",
    &descriptor_table_player_5fdata_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_player_5fdata_2eproto::offsets,
    file_level_metadata_player_5fdata_2eproto, file_level_enum_descriptors_player_5fdata_2eproto,
    file_level_service_descriptors_player_5fdata_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_player_5fdata_2eproto_getter() {
  return &descriptor_table_player_5fdata_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_player_5fdata_2eproto(&descriptor_table_player_5fdata_2eproto);
namespace pb {

// ===================================================================

class PlayerBaseData::_Internal {
 public:
};

PlayerBaseData::PlayerBaseData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pb.PlayerBaseData)
}
PlayerBaseData::PlayerBaseData(const PlayerBaseData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PlayerBaseData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.display_name_){}
    , decltype(_impl_.player_id_){}
    , decltype(_impl_.created_at_ms_){}
    , decltype(_impl_.last_login_at_ms_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.display_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.display_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_display_name().empty()) {
    _this->_impl_.display_name_.Set(from._internal_display_name(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.player_id_, &from._impl_.player_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.last_login_at_ms_) -
    reinterpret_cast<char*>(&_impl_.player_id_)) + sizeof(_impl_.last_login_at_ms_));
  // @@protoc_insertion_point(copy_constructor:pb.PlayerBaseData)
}

inline void PlayerBaseData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.display_name_){}
    , decltype(_impl_.player_id_){uint64_t{0u}}
    , decltype(_impl_.created_at_ms_){uint64_t{0u}}
    , decltype(_impl_.last_login_at_ms_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.display_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.display_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PlayerBaseData::~PlayerBaseData() {
  // @@protoc_insertion_point(destructor:pb.PlayerBaseData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PlayerBaseData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.display_name_.Destroy();
}

void PlayerBaseData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PlayerBaseData::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.PlayerBaseData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.display_name_.ClearToEmpty();
  ::memset(&_impl_.player_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.last_login_at_ms_) -
      reinterpret_cast<char*>(&_impl_.player_id_)) + sizeof(_impl_.last_login_at_ms_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerBaseData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 player_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.player_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string display_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_display_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "pb.PlayerBaseData.display_name"));
        } else
          goto handle_unusual;
        continue;
      // uint64 created_at_ms = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.created_at_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 last_login_at_ms = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.last_login_at_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlayerBaseData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.PlayerBaseData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 player_id = 1;
  if (this->_internal_player_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_player_id(), target);
  }

  // string display_name = 2;
  if (!this->_internal_display_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_display_name().data(), static_cast<int>(this->_internal_display_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb.PlayerBaseData.display_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_display_name(), target);
  }

  // uint64 created_at_ms = 3;
  if (this->_internal_created_at_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_created_at_ms(), target);
  }

  // uint64 last_login_at_ms = 4;
  if (this->_internal_last_login_at_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(4, this->_internal_last_login_at_ms(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.PlayerBaseData)
  return target;
}

size_t PlayerBaseData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.PlayerBaseData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string display_name = 2;
  if (!this->_internal_display_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_display_name());
  }

  // uint64 player_id = 1;
  if (this->_internal_player_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_player_id());
  }

  // uint64 created_at_ms = 3;
  if (this->_internal_created_at_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_created_at_ms());
  }

  // uint64 last_login_at_ms = 4;
  if (this->_internal_last_login_at_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_last_login_at_ms());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerBaseData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PlayerBaseData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerBaseData::GetClassData() const { return &_class_data_; }


void PlayerBaseData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PlayerBaseData*>(&to_msg);
  auto& from = static_cast<const PlayerBaseData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pb.PlayerBaseData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_display_name().empty()) {
    _this->_internal_set_display_name(from._internal_display_name());
  }
  if (from._internal_player_id() != 0) {
    _this->_internal_set_player_id(from._internal_player_id());
  }
  if (from._internal_created_at_ms() != 0) {
    _this->_internal_set_created_at_ms(from._internal_created_at_ms());
  }
  if (from._internal_last_login_at_ms() != 0) {
    _this->_internal_set_last_login_at_ms(from._internal_last_login_at_ms());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerBaseData::CopyFrom(const PlayerBaseData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.PlayerBaseData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerBaseData::IsInitialized() const {
  return true;
}

void PlayerBaseData::InternalSwap(PlayerBaseData* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.display_name_, lhs_arena,
      &other->_impl_.display_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerBaseData, _impl_.last_login_at_ms_)
      + sizeof(PlayerBaseData::_impl_.last_login_at_ms_)
      - PROTOBUF_FIELD_OFFSET(PlayerBaseData, _impl_.player_id_)>(
          reinterpret_cast<char*>(&_impl_.player_id_),
          reinterpret_cast<char*>(&other->_impl_.player_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerBaseData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_player_5fdata_2eproto_getter, &descriptor_table_player_5fdata_2eproto_once,
      file_level_metadata_player_5fdata_2eproto[0]);
}

// ===================================================================

class PlayerCoreData::_Internal {
 public:
};

PlayerCoreData::PlayerCoreData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pb.PlayerCoreData)
}
PlayerCoreData::PlayerCoreData(const PlayerCoreData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PlayerCoreData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.experience_){}
    , decltype(_impl_.login_count_){}
    , decltype(_impl_.level_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.experience_, &from._impl_.experience_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.level_) -
    reinterpret_cast<char*>(&_impl_.experience_)) + sizeof(_impl_.level_));
  // @@protoc_insertion_point(copy_constructor:pb.PlayerCoreData)
}

inline void PlayerCoreData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.experience_){uint64_t{0u}}
    , decltype(_impl_.login_count_){uint64_t{0u}}
    , decltype(_impl_.level_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PlayerCoreData::~PlayerCoreData() {
  // @@protoc_insertion_point(destructor:pb.PlayerCoreData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PlayerCoreData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PlayerCoreData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PlayerCoreData::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.PlayerCoreData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.experience_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.level_) -
      reinterpret_cast<char*>(&_impl_.experience_)) + sizeof(_impl_.level_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerCoreData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 level = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.level_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 experience = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.experience_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 login_count = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.login_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlayerCoreData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.PlayerCoreData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 level = 1;
  if (this->_internal_level() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_level(), target);
  }

  // uint64 experience = 2;
  if (this->_internal_experience() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_experience(), target);
  }

  // uint64 login_count = 3;
  if (this->_internal_login_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_login_count(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.PlayerCoreData)
  return target;
}

size_t PlayerCoreData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.PlayerCoreData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 experience = 2;
  if (this->_internal_experience() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_experience());
  }

  // uint64 login_count = 3;
  if (this->_internal_login_count() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_login_count());
  }

  // uint32 level = 1;
  if (this->_internal_level() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_level());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerCoreData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PlayerCoreData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerCoreData::GetClassData() const { return &_class_data_; }


void PlayerCoreData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PlayerCoreData*>(&to_msg);
  auto& from = static_cast<const PlayerCoreData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pb.PlayerCoreData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_experience() != 0) {
    _this->_internal_set_experience(from._internal_experience());
  }
  if (from._internal_login_count() != 0) {
    _this->_internal_set_login_count(from._internal_login_count());
  }
  if (from._internal_level() != 0) {
    _this->_internal_set_level(from._internal_level());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerCoreData::CopyFrom(const PlayerCoreData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.PlayerCoreData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerCoreData::IsInitialized() const {
  return true;
}

void PlayerCoreData::InternalSwap(PlayerCoreData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerCoreData, _impl_.level_)
      + sizeof(PlayerCoreData::_impl_.level_)
      - PROTOBUF_FIELD_OFFSET(PlayerCoreData, _impl_.experience_)>(
          reinterpret_cast<char*>(&_impl_.experience_),
          reinterpret_cast<char*>(&other->_impl_.experience_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerCoreData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_player_5fdata_2eproto_getter, &descriptor_table_player_5fdata_2eproto_once,
      file_level_metadata_player_5fdata_2eproto[1]);
}

// ===================================================================

class PlayerExtensionsData::_Internal {
 public:
};

PlayerExtensionsData::PlayerExtensionsData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pb.PlayerExtensionsData)
}
PlayerExtensionsData::PlayerExtensionsData(const PlayerExtensionsData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PlayerExtensionsData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.opaque_blob_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.opaque_blob_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.opaque_blob_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_opaque_blob().empty()) {
    _this->_impl_.opaque_blob_.Set(from._internal_opaque_blob(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:pb.PlayerExtensionsData)
}

inline void PlayerExtensionsData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.opaque_blob_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.opaque_blob_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.opaque_blob_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PlayerExtensionsData::~PlayerExtensionsData() {
  // @@protoc_insertion_point(destructor:pb.PlayerExtensionsData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PlayerExtensionsData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.opaque_blob_.Destroy();
}

void PlayerExtensionsData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PlayerExtensionsData::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.PlayerExtensionsData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.opaque_blob_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerExtensionsData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes opaque_blob = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_opaque_blob();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlayerExtensionsData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.PlayerExtensionsData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes opaque_blob = 1;
  if (!this->_internal_opaque_blob().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_opaque_blob(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.PlayerExtensionsData)
  return target;
}

size_t PlayerExtensionsData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.PlayerExtensionsData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes opaque_blob = 1;
  if (!this->_internal_opaque_blob().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_opaque_blob());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerExtensionsData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PlayerExtensionsData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerExtensionsData::GetClassData() const { return &_class_data_; }


void PlayerExtensionsData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PlayerExtensionsData*>(&to_msg);
  auto& from = static_cast<const PlayerExtensionsData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pb.PlayerExtensionsData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_opaque_blob().empty()) {
    _this->_internal_set_opaque_blob(from._internal_opaque_blob());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerExtensionsData::CopyFrom(const PlayerExtensionsData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.PlayerExtensionsData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerExtensionsData::IsInitialized() const {
  return true;
}

void PlayerExtensionsData::InternalSwap(PlayerExtensionsData* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.opaque_blob_, lhs_arena,
      &other->_impl_.opaque_blob_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerExtensionsData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_player_5fdata_2eproto_getter, &descriptor_table_player_5fdata_2eproto_once,
      file_level_metadata_player_5fdata_2eproto[2]);
}

// ===================================================================

class PlayerData::_Internal {
 public:
  static const ::pb::PlayerBaseData& base(const PlayerData* msg);
  static const ::pb::PlayerCoreData& core(const PlayerData* msg);
  static const ::pb::PlayerExtensionsData& extensions(const PlayerData* msg);
};

const ::pb::PlayerBaseData&
PlayerData::_Internal::base(const PlayerData* msg) {
  return *msg->_impl_.base_;
}
const ::pb::PlayerCoreData&
PlayerData::_Internal::core(const PlayerData* msg) {
  return *msg->_impl_.core_;
}
const ::pb::PlayerExtensionsData&
PlayerData::_Internal::extensions(const PlayerData* msg) {
  return *msg->_impl_.extensions_;
}
PlayerData::PlayerData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pb.PlayerData)
}
PlayerData::PlayerData(const PlayerData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PlayerData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.base_){nullptr}
    , decltype(_impl_.core_){nullptr}
    , decltype(_impl_.extensions_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_base()) {
    _this->_impl_.base_ = new ::pb::PlayerBaseData(*from._impl_.base_);
  }
  if (from._internal_has_core()) {
    _this->_impl_.core_ = new ::pb::PlayerCoreData(*from._impl_.core_);
  }
  if (from._internal_has_extensions()) {
    _this->_impl_.extensions_ = new ::pb::PlayerExtensionsData(*from._impl_.extensions_);
  }
  // @@protoc_insertion_point(copy_constructor:pb.PlayerData)
}

inline void PlayerData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.base_){nullptr}
    , decltype(_impl_.core_){nullptr}
    , decltype(_impl_.extensions_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PlayerData::~PlayerData() {
  // @@protoc_insertion_point(destructor:pb.PlayerData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PlayerData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.base_;
  if (this != internal_default_instance()) delete _impl_.core_;
  if (this != internal_default_instance()) delete _impl_.extensions_;
}

void PlayerData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PlayerData::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.PlayerData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.base_ != nullptr) {
    delete _impl_.base_;
  }
  _impl_.base_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.core_ != nullptr) {
    delete _impl_.core_;
  }
  _impl_.core_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.extensions_ != nullptr) {
    delete _impl_.extensions_;
  }
  _impl_.extensions_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .pb.PlayerBaseData base = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_base(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .pb.PlayerCoreData core = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_core(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .pb.PlayerExtensionsData extensions = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_extensions(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlayerData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.PlayerData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .pb.PlayerBaseData base = 1;
  if (this->_internal_has_base()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::base(this),
        _Internal::base(this).GetCachedSize(), target, stream);
  }

  // .pb.PlayerCoreData core = 2;
  if (this->_internal_has_core()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::core(this),
        _Internal::core(this).GetCachedSize(), target, stream);
  }

  // .pb.PlayerExtensionsData extensions = 3;
  if (this->_internal_has_extensions()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::extensions(this),
        _Internal::extensions(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.PlayerData)
  return target;
}

size_t PlayerData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.PlayerData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .pb.PlayerBaseData base = 1;
  if (this->_internal_has_base()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.base_);
  }

  // .pb.PlayerCoreData core = 2;
  if (this->_internal_has_core()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.core_);
  }

  // .pb.PlayerExtensionsData extensions = 3;
  if (this->_internal_has_extensions()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.extensions_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PlayerData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerData::GetClassData() const { return &_class_data_; }


void PlayerData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PlayerData*>(&to_msg);
  auto& from = static_cast<const PlayerData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pb.PlayerData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_base()) {
    _this->_internal_mutable_base()->::pb::PlayerBaseData::MergeFrom(
        from._internal_base());
  }
  if (from._internal_has_core()) {
    _this->_internal_mutable_core()->::pb::PlayerCoreData::MergeFrom(
        from._internal_core());
  }
  if (from._internal_has_extensions()) {
    _this->_internal_mutable_extensions()->::pb::PlayerExtensionsData::MergeFrom(
        from._internal_extensions());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerData::CopyFrom(const PlayerData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.PlayerData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerData::IsInitialized() const {
  return true;
}

void PlayerData::InternalSwap(PlayerData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerData, _impl_.extensions_)
      + sizeof(PlayerData::_impl_.extensions_)
      - PROTOBUF_FIELD_OFFSET(PlayerData, _impl_.base_)>(
          reinterpret_cast<char*>(&_impl_.base_),
          reinterpret_cast<char*>(&other->_impl_.base_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_player_5fdata_2eproto_getter, &descriptor_table_player_5fdata_2eproto_once,
      file_level_metadata_player_5fdata_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::pb::PlayerBaseData*
Arena::CreateMaybeMessage< ::pb::PlayerBaseData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pb::PlayerBaseData >(arena);
}
template<> PROTOBUF_NOINLINE ::pb::PlayerCoreData*
Arena::CreateMaybeMessage< ::pb::PlayerCoreData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pb::PlayerCoreData >(arena);
}
template<> PROTOBUF_NOINLINE ::pb::PlayerExtensionsData*
Arena::CreateMaybeMessage< ::pb::PlayerExtensionsData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pb::PlayerExtensionsData >(arena);
}
template<> PROTOBUF_NOINLINE ::pb::PlayerData*
Arena::CreateMaybeMessage< ::pb::PlayerData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pb::PlayerData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
