// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player_data.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_player_5fdata_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_player_5fdata_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_player_5fdata_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_player_5fdata_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_player_5fdata_2eproto;
namespace pb {
class PlayerBaseData;
struct PlayerBaseDataDefaultTypeInternal;
extern PlayerBaseDataDefaultTypeInternal _PlayerBaseData_default_instance_;
class PlayerCoreData;
struct PlayerCoreDataDefaultTypeInternal;
extern PlayerCoreDataDefaultTypeInternal _PlayerCoreData_default_instance_;
class PlayerData;
struct PlayerDataDefaultTypeInternal;
extern PlayerDataDefaultTypeInternal _PlayerData_default_instance_;
class PlayerExtensionsData;
struct PlayerExtensionsDataDefaultTypeInternal;
extern PlayerExtensionsDataDefaultTypeInternal _PlayerExtensionsData_default_instance_;
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> ::pb::PlayerBaseData* Arena::CreateMaybeMessage<::pb::PlayerBaseData>(Arena*);
template<> ::pb::PlayerCoreData* Arena::CreateMaybeMessage<::pb::PlayerCoreData>(Arena*);
template<> ::pb::PlayerData* Arena::CreateMaybeMessage<::pb::PlayerData>(Arena*);
template<> ::pb::PlayerExtensionsData* Arena::CreateMaybeMessage<::pb::PlayerExtensionsData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pb {

// ===================================================================

class PlayerBaseData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.PlayerBaseData) */ {
 public:
  inline PlayerBaseData() : PlayerBaseData(nullptr) {}
  ~PlayerBaseData() override;
  explicit PROTOBUF_CONSTEXPR PlayerBaseData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerBaseData(const PlayerBaseData& from);
  PlayerBaseData(PlayerBaseData&& from) noexcept
    : PlayerBaseData() {
    *this = ::std::move(from);
  }

  inline PlayerBaseData& operator=(const PlayerBaseData& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerBaseData& operator=(PlayerBaseData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerBaseData& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerBaseData* internal_default_instance() {
    return reinterpret_cast<const PlayerBaseData*>(
               &_PlayerBaseData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PlayerBaseData& a, PlayerBaseData& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerBaseData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerBaseData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerBaseData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerBaseData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerBaseData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerBaseData& from) {
    PlayerBaseData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerBaseData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.PlayerBaseData";
  }
  protected:
  explicit PlayerBaseData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDisplayNameFieldNumber = 2,
    kPlayerIdFieldNumber = 1,
    kCreatedAtMsFieldNumber = 3,
    kLastLoginAtMsFieldNumber = 4,
  };
  // string display_name = 2;
  void clear_display_name();
  const std::string& display_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_display_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_display_name();
  PROTOBUF_NODISCARD std::string* release_display_name();
  void set_allocated_display_name(std::string* display_name);
  private:
  const std::string& _internal_display_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_display_name(const std::string& value);
  std::string* _internal_mutable_display_name();
  public:

  // uint64 player_id = 1;
  void clear_player_id();
  uint64_t player_id() const;
  void set_player_id(uint64_t value);
  private:
  uint64_t _internal_player_id() const;
  void _internal_set_player_id(uint64_t value);
  public:

  // uint64 created_at_ms = 3;
  void clear_created_at_ms();
  uint64_t created_at_ms() const;
  void set_created_at_ms(uint64_t value);
  private:
  uint64_t _internal_created_at_ms() const;
  void _internal_set_created_at_ms(uint64_t value);
  public:

  // uint64 last_login_at_ms = 4;
  void clear_last_login_at_ms();
  uint64_t last_login_at_ms() const;
  void set_last_login_at_ms(uint64_t value);
  private:
  uint64_t _internal_last_login_at_ms() const;
  void _internal_set_last_login_at_ms(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:pb.PlayerBaseData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr display_name_;
    uint64_t player_id_;
    uint64_t created_at_ms_;
    uint64_t last_login_at_ms_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_player_5fdata_2eproto;
};
// -------------------------------------------------------------------

class PlayerCoreData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.PlayerCoreData) */ {
 public:
  inline PlayerCoreData() : PlayerCoreData(nullptr) {}
  ~PlayerCoreData() override;
  explicit PROTOBUF_CONSTEXPR PlayerCoreData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerCoreData(const PlayerCoreData& from);
  PlayerCoreData(PlayerCoreData&& from) noexcept
    : PlayerCoreData() {
    *this = ::std::move(from);
  }

  inline PlayerCoreData& operator=(const PlayerCoreData& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerCoreData& operator=(PlayerCoreData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerCoreData& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerCoreData* internal_default_instance() {
    return reinterpret_cast<const PlayerCoreData*>(
               &_PlayerCoreData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PlayerCoreData& a, PlayerCoreData& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerCoreData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerCoreData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerCoreData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerCoreData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerCoreData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerCoreData& from) {
    PlayerCoreData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerCoreData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.PlayerCoreData";
  }
  protected:
  explicit PlayerCoreData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kExperienceFieldNumber = 2,
    kLoginCountFieldNumber = 3,
    kLevelFieldNumber = 1,
  };
  // uint64 experience = 2;
  void clear_experience();
  uint64_t experience() const;
  void set_experience(uint64_t value);
  private:
  uint64_t _internal_experience() const;
  void _internal_set_experience(uint64_t value);
  public:

  // uint64 login_count = 3;
  void clear_login_count();
  uint64_t login_count() const;
  void set_login_count(uint64_t value);
  private:
  uint64_t _internal_login_count() const;
  void _internal_set_login_count(uint64_t value);
  public:

  // uint32 level = 1;
  void clear_level();
  uint32_t level() const;
  void set_level(uint32_t value);
  private:
  uint32_t _internal_level() const;
  void _internal_set_level(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:pb.PlayerCoreData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t experience_;
    uint64_t login_count_;
    uint32_t level_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_player_5fdata_2eproto;
};
// -------------------------------------------------------------------

class PlayerExtensionsData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.PlayerExtensionsData) */ {
 public:
  inline PlayerExtensionsData() : PlayerExtensionsData(nullptr) {}
  ~PlayerExtensionsData() override;
  explicit PROTOBUF_CONSTEXPR PlayerExtensionsData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerExtensionsData(const PlayerExtensionsData& from);
  PlayerExtensionsData(PlayerExtensionsData&& from) noexcept
    : PlayerExtensionsData() {
    *this = ::std::move(from);
  }

  inline PlayerExtensionsData& operator=(const PlayerExtensionsData& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerExtensionsData& operator=(PlayerExtensionsData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerExtensionsData& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerExtensionsData* internal_default_instance() {
    return reinterpret_cast<const PlayerExtensionsData*>(
               &_PlayerExtensionsData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PlayerExtensionsData& a, PlayerExtensionsData& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerExtensionsData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerExtensionsData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerExtensionsData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerExtensionsData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerExtensionsData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerExtensionsData& from) {
    PlayerExtensionsData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerExtensionsData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.PlayerExtensionsData";
  }
  protected:
  explicit PlayerExtensionsData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOpaqueBlobFieldNumber = 1,
  };
  // bytes opaque_blob = 1;
  void clear_opaque_blob();
  const std::string& opaque_blob() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_opaque_blob(ArgT0&& arg0, ArgT... args);
  std::string* mutable_opaque_blob();
  PROTOBUF_NODISCARD std::string* release_opaque_blob();
  void set_allocated_opaque_blob(std::string* opaque_blob);
  private:
  const std::string& _internal_opaque_blob() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_opaque_blob(const std::string& value);
  std::string* _internal_mutable_opaque_blob();
  public:

  // @@protoc_insertion_point(class_scope:pb.PlayerExtensionsData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr opaque_blob_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_player_5fdata_2eproto;
};
// -------------------------------------------------------------------

class PlayerData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.PlayerData) */ {
 public:
  inline PlayerData() : PlayerData(nullptr) {}
  ~PlayerData() override;
  explicit PROTOBUF_CONSTEXPR PlayerData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerData(const PlayerData& from);
  PlayerData(PlayerData&& from) noexcept
    : PlayerData() {
    *this = ::std::move(from);
  }

  inline PlayerData& operator=(const PlayerData& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerData& operator=(PlayerData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerData& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerData* internal_default_instance() {
    return reinterpret_cast<const PlayerData*>(
               &_PlayerData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PlayerData& a, PlayerData& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerData& from) {
    PlayerData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.PlayerData";
  }
  protected:
  explicit PlayerData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBaseFieldNumber = 1,
    kCoreFieldNumber = 2,
    kExtensionsFieldNumber = 3,
  };
  // .pb.PlayerBaseData base = 1;
  bool has_base() const;
  private:
  bool _internal_has_base() const;
  public:
  void clear_base();
  const ::pb::PlayerBaseData& base() const;
  PROTOBUF_NODISCARD ::pb::PlayerBaseData* release_base();
  ::pb::PlayerBaseData* mutable_base();
  void set_allocated_base(::pb::PlayerBaseData* base);
  private:
  const ::pb::PlayerBaseData& _internal_base() const;
  ::pb::PlayerBaseData* _internal_mutable_base();
  public:
  void unsafe_arena_set_allocated_base(
      ::pb::PlayerBaseData* base);
  ::pb::PlayerBaseData* unsafe_arena_release_base();

  // .pb.PlayerCoreData core = 2;
  bool has_core() const;
  private:
  bool _internal_has_core() const;
  public:
  void clear_core();
  const ::pb::PlayerCoreData& core() const;
  PROTOBUF_NODISCARD ::pb::PlayerCoreData* release_core();
  ::pb::PlayerCoreData* mutable_core();
  void set_allocated_core(::pb::PlayerCoreData* core);
  private:
  const ::pb::PlayerCoreData& _internal_core() const;
  ::pb::PlayerCoreData* _internal_mutable_core();
  public:
  void unsafe_arena_set_allocated_core(
      ::pb::PlayerCoreData* core);
  ::pb::PlayerCoreData* unsafe_arena_release_core();

  // .pb.PlayerExtensionsData extensions = 3;
  bool has_extensions() const;
  private:
  bool _internal_has_extensions() const;
  public:
  void clear_extensions();
  const ::pb::PlayerExtensionsData& extensions() const;
  PROTOBUF_NODISCARD ::pb::PlayerExtensionsData* release_extensions();
  ::pb::PlayerExtensionsData* mutable_extensions();
  void set_allocated_extensions(::pb::PlayerExtensionsData* extensions);
  private:
  const ::pb::PlayerExtensionsData& _internal_extensions() const;
  ::pb::PlayerExtensionsData* _internal_mutable_extensions();
  public:
  void unsafe_arena_set_allocated_extensions(
      ::pb::PlayerExtensionsData* extensions);
  ::pb::PlayerExtensionsData* unsafe_arena_release_extensions();

  // @@protoc_insertion_point(class_scope:pb.PlayerData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::pb::PlayerBaseData* base_;
    ::pb::PlayerCoreData* core_;
    ::pb::PlayerExtensionsData* extensions_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_player_5fdata_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PlayerBaseData

// uint64 player_id = 1;
inline void PlayerBaseData::clear_player_id() {
  _impl_.player_id_ = uint64_t{0u};
}
inline uint64_t PlayerBaseData::_internal_player_id() const {
  return _impl_.player_id_;
}
inline uint64_t PlayerBaseData::player_id() const {
  // @@protoc_insertion_point(field_get:pb.PlayerBaseData.player_id)
  return _internal_player_id();
}
inline void PlayerBaseData::_internal_set_player_id(uint64_t value) {
  
  _impl_.player_id_ = value;
}
inline void PlayerBaseData::set_player_id(uint64_t value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:pb.PlayerBaseData.player_id)
}

// string display_name = 2;
inline void PlayerBaseData::clear_display_name() {
  _impl_.display_name_.ClearToEmpty();
}
inline const std::string& PlayerBaseData::display_name() const {
  // @@protoc_insertion_point(field_get:pb.PlayerBaseData.display_name)
  return _internal_display_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PlayerBaseData::set_display_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.display_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb.PlayerBaseData.display_name)
}
inline std::string* PlayerBaseData::mutable_display_name() {
  std::string* _s = _internal_mutable_display_name();
  // @@protoc_insertion_point(field_mutable:pb.PlayerBaseData.display_name)
  return _s;
}
inline const std::string& PlayerBaseData::_internal_display_name() const {
  return _impl_.display_name_.Get();
}
inline void PlayerBaseData::_internal_set_display_name(const std::string& value) {
  
  _impl_.display_name_.Set(value, GetArenaForAllocation());
}
inline std::string* PlayerBaseData::_internal_mutable_display_name() {
  
  return _impl_.display_name_.Mutable(GetArenaForAllocation());
}
inline std::string* PlayerBaseData::release_display_name() {
  // @@protoc_insertion_point(field_release:pb.PlayerBaseData.display_name)
  return _impl_.display_name_.Release();
}
inline void PlayerBaseData::set_allocated_display_name(std::string* display_name) {
  if (display_name != nullptr) {
    
  } else {
    
  }
  _impl_.display_name_.SetAllocated(display_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.display_name_.IsDefault()) {
    _impl_.display_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb.PlayerBaseData.display_name)
}

// uint64 created_at_ms = 3;
inline void PlayerBaseData::clear_created_at_ms() {
  _impl_.created_at_ms_ = uint64_t{0u};
}
inline uint64_t PlayerBaseData::_internal_created_at_ms() const {
  return _impl_.created_at_ms_;
}
inline uint64_t PlayerBaseData::created_at_ms() const {
  // @@protoc_insertion_point(field_get:pb.PlayerBaseData.created_at_ms)
  return _internal_created_at_ms();
}
inline void PlayerBaseData::_internal_set_created_at_ms(uint64_t value) {
  
  _impl_.created_at_ms_ = value;
}
inline void PlayerBaseData::set_created_at_ms(uint64_t value) {
  _internal_set_created_at_ms(value);
  // @@protoc_insertion_point(field_set:pb.PlayerBaseData.created_at_ms)
}

// uint64 last_login_at_ms = 4;
inline void PlayerBaseData::clear_last_login_at_ms() {
  _impl_.last_login_at_ms_ = uint64_t{0u};
}
inline uint64_t PlayerBaseData::_internal_last_login_at_ms() const {
  return _impl_.last_login_at_ms_;
}
inline uint64_t PlayerBaseData::last_login_at_ms() const {
  // @@protoc_insertion_point(field_get:pb.PlayerBaseData.last_login_at_ms)
  return _internal_last_login_at_ms();
}
inline void PlayerBaseData::_internal_set_last_login_at_ms(uint64_t value) {
  
  _impl_.last_login_at_ms_ = value;
}
inline void PlayerBaseData::set_last_login_at_ms(uint64_t value) {
  _internal_set_last_login_at_ms(value);
  // @@protoc_insertion_point(field_set:pb.PlayerBaseData.last_login_at_ms)
}

// -------------------------------------------------------------------

// PlayerCoreData

// uint32 level = 1;
inline void PlayerCoreData::clear_level() {
  _impl_.level_ = 0u;
}
inline uint32_t PlayerCoreData::_internal_level() const {
  return _impl_.level_;
}
inline uint32_t PlayerCoreData::level() const {
  // @@protoc_insertion_point(field_get:pb.PlayerCoreData.level)
  return _internal_level();
}
inline void PlayerCoreData::_internal_set_level(uint32_t value) {
  
  _impl_.level_ = value;
}
inline void PlayerCoreData::set_level(uint32_t value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:pb.PlayerCoreData.level)
}

// uint64 experience = 2;
inline void PlayerCoreData::clear_experience() {
  _impl_.experience_ = uint64_t{0u};
}
inline uint64_t PlayerCoreData::_internal_experience() const {
  return _impl_.experience_;
}
inline uint64_t PlayerCoreData::experience() const {
  // @@protoc_insertion_point(field_get:pb.PlayerCoreData.experience)
  return _internal_experience();
}
inline void PlayerCoreData::_internal_set_experience(uint64_t value) {
  
  _impl_.experience_ = value;
}
inline void PlayerCoreData::set_experience(uint64_t value) {
  _internal_set_experience(value);
  // @@protoc_insertion_point(field_set:pb.PlayerCoreData.experience)
}

// uint64 login_count = 3;
inline void PlayerCoreData::clear_login_count() {
  _impl_.login_count_ = uint64_t{0u};
}
inline uint64_t PlayerCoreData::_internal_login_count() const {
  return _impl_.login_count_;
}
inline uint64_t PlayerCoreData::login_count() const {
  // @@protoc_insertion_point(field_get:pb.PlayerCoreData.login_count)
  return _internal_login_count();
}
inline void PlayerCoreData::_internal_set_login_count(uint64_t value) {
  
  _impl_.login_count_ = value;
}
inline void PlayerCoreData::set_login_count(uint64_t value) {
  _internal_set_login_count(value);
  // @@protoc_insertion_point(field_set:pb.PlayerCoreData.login_count)
}

// -------------------------------------------------------------------

// PlayerExtensionsData

// bytes opaque_blob = 1;
inline void PlayerExtensionsData::clear_opaque_blob() {
  _impl_.opaque_blob_.ClearToEmpty();
}
inline const std::string& PlayerExtensionsData::opaque_blob() const {
  // @@protoc_insertion_point(field_get:pb.PlayerExtensionsData.opaque_blob)
  return _internal_opaque_blob();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PlayerExtensionsData::set_opaque_blob(ArgT0&& arg0, ArgT... args) {
 
 _impl_.opaque_blob_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb.PlayerExtensionsData.opaque_blob)
}
inline std::string* PlayerExtensionsData::mutable_opaque_blob() {
  std::string* _s = _internal_mutable_opaque_blob();
  // @@protoc_insertion_point(field_mutable:pb.PlayerExtensionsData.opaque_blob)
  return _s;
}
inline const std::string& PlayerExtensionsData::_internal_opaque_blob() const {
  return _impl_.opaque_blob_.Get();
}
inline void PlayerExtensionsData::_internal_set_opaque_blob(const std::string& value) {
  
  _impl_.opaque_blob_.Set(value, GetArenaForAllocation());
}
inline std::string* PlayerExtensionsData::_internal_mutable_opaque_blob() {
  
  return _impl_.opaque_blob_.Mutable(GetArenaForAllocation());
}
inline std::string* PlayerExtensionsData::release_opaque_blob() {
  // @@protoc_insertion_point(field_release:pb.PlayerExtensionsData.opaque_blob)
  return _impl_.opaque_blob_.Release();
}
inline void PlayerExtensionsData::set_allocated_opaque_blob(std::string* opaque_blob) {
  if (opaque_blob != nullptr) {
    
  } else {
    
  }
  _impl_.opaque_blob_.SetAllocated(opaque_blob, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.opaque_blob_.IsDefault()) {
    _impl_.opaque_blob_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb.PlayerExtensionsData.opaque_blob)
}

// -------------------------------------------------------------------

// PlayerData

// .pb.PlayerBaseData base = 1;
inline bool PlayerData::_internal_has_base() const {
  return this != internal_default_instance() && _impl_.base_ != nullptr;
}
inline bool PlayerData::has_base() const {
  return _internal_has_base();
}
inline void PlayerData::clear_base() {
  if (GetArenaForAllocation() == nullptr && _impl_.base_ != nullptr) {
    delete _impl_.base_;
  }
  _impl_.base_ = nullptr;
}
inline const ::pb::PlayerBaseData& PlayerData::_internal_base() const {
  const ::pb::PlayerBaseData* p = _impl_.base_;
  return p != nullptr ? *p : reinterpret_cast<const ::pb::PlayerBaseData&>(
      ::pb::_PlayerBaseData_default_instance_);
}
inline const ::pb::PlayerBaseData& PlayerData::base() const {
  // @@protoc_insertion_point(field_get:pb.PlayerData.base)
  return _internal_base();
}
inline void PlayerData::unsafe_arena_set_allocated_base(
    ::pb::PlayerBaseData* base) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.base_);
  }
  _impl_.base_ = base;
  if (base) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:pb.PlayerData.base)
}
inline ::pb::PlayerBaseData* PlayerData::release_base() {
  
  ::pb::PlayerBaseData* temp = _impl_.base_;
  _impl_.base_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::pb::PlayerBaseData* PlayerData::unsafe_arena_release_base() {
  // @@protoc_insertion_point(field_release:pb.PlayerData.base)
  
  ::pb::PlayerBaseData* temp = _impl_.base_;
  _impl_.base_ = nullptr;
  return temp;
}
inline ::pb::PlayerBaseData* PlayerData::_internal_mutable_base() {
  
  if (_impl_.base_ == nullptr) {
    auto* p = CreateMaybeMessage<::pb::PlayerBaseData>(GetArenaForAllocation());
    _impl_.base_ = p;
  }
  return _impl_.base_;
}
inline ::pb::PlayerBaseData* PlayerData::mutable_base() {
  ::pb::PlayerBaseData* _msg = _internal_mutable_base();
  // @@protoc_insertion_point(field_mutable:pb.PlayerData.base)
  return _msg;
}
inline void PlayerData::set_allocated_base(::pb::PlayerBaseData* base) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.base_;
  }
  if (base) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(base);
    if (message_arena != submessage_arena) {
      base = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, base, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.base_ = base;
  // @@protoc_insertion_point(field_set_allocated:pb.PlayerData.base)
}

// .pb.PlayerCoreData core = 2;
inline bool PlayerData::_internal_has_core() const {
  return this != internal_default_instance() && _impl_.core_ != nullptr;
}
inline bool PlayerData::has_core() const {
  return _internal_has_core();
}
inline void PlayerData::clear_core() {
  if (GetArenaForAllocation() == nullptr && _impl_.core_ != nullptr) {
    delete _impl_.core_;
  }
  _impl_.core_ = nullptr;
}
inline const ::pb::PlayerCoreData& PlayerData::_internal_core() const {
  const ::pb::PlayerCoreData* p = _impl_.core_;
  return p != nullptr ? *p : reinterpret_cast<const ::pb::PlayerCoreData&>(
      ::pb::_PlayerCoreData_default_instance_);
}
inline const ::pb::PlayerCoreData& PlayerData::core() const {
  // @@protoc_insertion_point(field_get:pb.PlayerData.core)
  return _internal_core();
}
inline void PlayerData::unsafe_arena_set_allocated_core(
    ::pb::PlayerCoreData* core) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.core_);
  }
  _impl_.core_ = core;
  if (core) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:pb.PlayerData.core)
}
inline ::pb::PlayerCoreData* PlayerData::release_core() {
  
  ::pb::PlayerCoreData* temp = _impl_.core_;
  _impl_.core_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::pb::PlayerCoreData* PlayerData::unsafe_arena_release_core() {
  // @@protoc_insertion_point(field_release:pb.PlayerData.core)
  
  ::pb::PlayerCoreData* temp = _impl_.core_;
  _impl_.core_ = nullptr;
  return temp;
}
inline ::pb::PlayerCoreData* PlayerData::_internal_mutable_core() {
  
  if (_impl_.core_ == nullptr) {
    auto* p = CreateMaybeMessage<::pb::PlayerCoreData>(GetArenaForAllocation());
    _impl_.core_ = p;
  }
  return _impl_.core_;
}
inline ::pb::PlayerCoreData* PlayerData::mutable_core() {
  ::pb::PlayerCoreData* _msg = _internal_mutable_core();
  // @@protoc_insertion_point(field_mutable:pb.PlayerData.core)
  return _msg;
}
inline void PlayerData::set_allocated_core(::pb::PlayerCoreData* core) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.core_;
  }
  if (core) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(core);
    if (message_arena != submessage_arena) {
      core = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, core, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.core_ = core;
  // @@protoc_insertion_point(field_set_allocated:pb.PlayerData.core)
}

// .pb.PlayerExtensionsData extensions = 3;
inline bool PlayerData::_internal_has_extensions() const {
  return this != internal_default_instance() && _impl_.extensions_ != nullptr;
}
inline bool PlayerData::has_extensions() const {
  return _internal_has_extensions();
}
inline void PlayerData::clear_extensions() {
  if (GetArenaForAllocation() == nullptr && _impl_.extensions_ != nullptr) {
    delete _impl_.extensions_;
  }
  _impl_.extensions_ = nullptr;
}
inline const ::pb::PlayerExtensionsData& PlayerData::_internal_extensions() const {
  const ::pb::PlayerExtensionsData* p = _impl_.extensions_;
  return p != nullptr ? *p : reinterpret_cast<const ::pb::PlayerExtensionsData&>(
      ::pb::_PlayerExtensionsData_default_instance_);
}
inline const ::pb::PlayerExtensionsData& PlayerData::extensions() const {
  // @@protoc_insertion_point(field_get:pb.PlayerData.extensions)
  return _internal_extensions();
}
inline void PlayerData::unsafe_arena_set_allocated_extensions(
    ::pb::PlayerExtensionsData* extensions) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.extensions_);
  }
  _impl_.extensions_ = extensions;
  if (extensions) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:pb.PlayerData.extensions)
}
inline ::pb::PlayerExtensionsData* PlayerData::release_extensions() {
  
  ::pb::PlayerExtensionsData* temp = _impl_.extensions_;
  _impl_.extensions_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::pb::PlayerExtensionsData* PlayerData::unsafe_arena_release_extensions() {
  // @@protoc_insertion_point(field_release:pb.PlayerData.extensions)
  
  ::pb::PlayerExtensionsData* temp = _impl_.extensions_;
  _impl_.extensions_ = nullptr;
  return temp;
}
inline ::pb::PlayerExtensionsData* PlayerData::_internal_mutable_extensions() {
  
  if (_impl_.extensions_ == nullptr) {
    auto* p = CreateMaybeMessage<::pb::PlayerExtensionsData>(GetArenaForAllocation());
    _impl_.extensions_ = p;
  }
  return _impl_.extensions_;
}
inline ::pb::PlayerExtensionsData* PlayerData::mutable_extensions() {
  ::pb::PlayerExtensionsData* _msg = _internal_mutable_extensions();
  // @@protoc_insertion_point(field_mutable:pb.PlayerData.extensions)
  return _msg;
}
inline void PlayerData::set_allocated_extensions(::pb::PlayerExtensionsData* extensions) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.extensions_;
  }
  if (extensions) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(extensions);
    if (message_arena != submessage_arena) {
      extensions = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, extensions, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.extensions_ = extensions;
  // @@protoc_insertion_point(field_set_allocated:pb.PlayerData.extensions)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_player_5fdata_2eproto
